namespace offsets
{
	namespace AUltra_Dynamic_Sky_BP_C
	{
			constexpr auto UberGraphFrame = 0x220; // Size: 8, Type: struct FPointerToUberGraphFrame
			constexpr auto moon_plane = 0x228; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto Arrow = 0x230; // Size: 8, Type: struct UArrowComponent*
			constexpr auto Sun_Root = 0x238; // Size: 8, Type: struct UArrowComponent*
			constexpr auto Ultra_Dynamic_Sky_Sphere = 0x240; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto DefaultSceneRoot = 0x248; // Size: 8, Type: struct USceneComponent*
			constexpr auto Direction Light (Sun) = 0x250; // Size: 8, Type: struct ADirectionalLight*
			constexpr auto UDM_mat = 0x258; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto Refresh Settings = 0x260; // Size: 1, Type: bool
			constexpr auto Cloud Speed = 0x264; // Size: 4, Type: float
			constexpr auto Cloud Density = 0x268; // Size: 4, Type: float
			constexpr auto Cloud Wisps Opacity = 0x26c; // Size: 4, Type: float
			constexpr auto Horizon Base Color Curve = 0x270; // Size: 16, Type: struct TArray<struct UCurveLinearColor*>
			constexpr auto Zenith Base Color Curve = 0x280; // Size: 16, Type: struct TArray<struct UCurveLinearColor*>
			constexpr auto Cloud Light Color Curve = 0x290; // Size: 16, Type: struct TArray<struct UCurveLinearColor*>
			constexpr auto Cloud Dark Color Curve = 0x2a0; // Size: 16, Type: struct TArray<struct UCurveLinearColor*>
			constexpr auto Time of Day = 0x2b0; // Size: 4, Type: float
			constexpr auto Sun Color Curve = 0x2b8; // Size: 16, Type: struct TArray<struct UCurveLinearColor*>
			constexpr auto Shine Intensity Curve = 0x2c8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto Saturation = 0x2d0; // Size: 4, Type: float
			constexpr auto Sun Cloudy Color Curve = 0x2d8; // Size: 8, Type: struct UCurveLinearColor*
			constexpr auto Exponential Height Fog = 0x2e0; // Size: 8, Type: struct AExponentialHeightFog*
			constexpr auto Stars Intensity Curve = 0x2e8; // Size: 8, Type: struct UCurveFloat*
			constexpr auto Cloud Phase = 0x2f0; // Size: 4, Type: float
			constexpr auto Moon Scale = 0x2f4; // Size: 4, Type: float
			constexpr auto Moon Inclination = 0x2f8; // Size: 4, Type: float
			constexpr auto Moon Phase = 0x2fc; // Size: 4, Type: float
			constexpr auto Automatically Set Advanced Settings using Time of Day = 0x300; // Size: 1, Type: bool
			constexpr auto Stars Visibility = 0x304; // Size: 4, Type: float
			constexpr auto Moon Intensity = 0x308; // Size: 4, Type: float
			constexpr auto Moon Position = 0x30c; // Size: 4, Type: float
			constexpr auto Sun Angle = 0x310; // Size: 4, Type: float
			constexpr auto Horizon Base Color = 0x314; // Size: 16, Type: struct FLinearColor
			constexpr auto Zenith Base Color = 0x324; // Size: 16, Type: struct FLinearColor
			constexpr auto Cloud Light Color = 0x334; // Size: 16, Type: struct FLinearColor
			constexpr auto Cloud Dark Color = 0x344; // Size: 16, Type: struct FLinearColor
			constexpr auto Sun Color = 0x354; // Size: 16, Type: struct FLinearColor
			constexpr auto Cloud Shine Intensity = 0x364; // Size: 4, Type: float
			constexpr auto Sun Light Color = 0x368; // Size: 16, Type: struct FLinearColor
			constexpr auto Day Length = 0x378; // Size: 4, Type: float
			constexpr auto Moon Position Curve = 0x380; // Size: 8, Type: struct UCurveFloat*
			constexpr auto Night Cycle = 0x388; // Size: 1, Type: bool
			constexpr auto Simulate Cloud Density Changes = 0x389; // Size: 1, Type: bool
			constexpr auto Cloud Density Shift Frequency (min) = 0x38c; // Size: 4, Type: float
			constexpr auto Cloud Density Shift Frequency (max) = 0x390; // Size: 4, Type: float
			constexpr auto Cloud Density_target = 0x394; // Size: 4, Type: float
			constexpr auto Cloud Density Change (Smoothing) = 0x398; // Size: 4, Type: float
			constexpr auto Cloud Opacity = 0x39c; // Size: 4, Type: float
			constexpr auto Overall Intensity = 0x3a0; // Size: 4, Type: float
			constexpr auto Sun Brightness = 0x3a4; // Size: 4, Type: float
			constexpr auto Moon Color = 0x3a8; // Size: 16, Type: struct FLinearColor
			constexpr auto Shine Variation = 0x3b8; // Size: 4, Type: float
			constexpr auto Sun Lighting Intensity = 0x3bc; // Size: 4, Type: float
			constexpr auto Sun Highlight Radius_curve = 0x3c0; // Size: 8, Type: struct UCurveFloat*
			constexpr auto Sun Highlight Radius = 0x3c8; // Size: 4, Type: float
			constexpr auto First Day = 0x3cc; // Size: 1, Type: bool
			constexpr auto Simulate Moon Phase Changes = 0x3cd; // Size: 1, Type: bool
			constexpr auto Stars_Intensity = 0x3d0; // Size: 4, Type: float
			constexpr auto Stars_Color = 0x3d4; // Size: 16, Type: struct FLinearColor
			constexpr auto Moon Orbit Offset = 0x3e4; // Size: 4, Type: float
			constexpr auto Sun Rotation = 0x3e8; // Size: 12, Type: struct FRotator
			constexpr auto Sun Radius = 0x3f4; // Size: 4, Type: float
			constexpr auto Cloud Shadows MID = 0x3f8; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto Use Cloud Shadows = 0x400; // Size: 1, Type: bool
			constexpr auto Cloud Shadows Scale = 0x404; // Size: 4, Type: float
			constexpr auto Cloud Shadows Intensity = 0x408; // Size: 4, Type: float
			constexpr auto Moon Light = 0x410; // Size: 8, Type: struct ADirectionalLight*
			constexpr auto Manually Select Sun Color = 0x418; // Size: 1, Type: bool
			constexpr auto Automatically Set Moon Light Rotation = 0x419; // Size: 1, Type: bool
			constexpr auto Automatically Set Sun Light Rotation = 0x41a; // Size: 1, Type: bool
			constexpr auto Moonlight Intensity = 0x41c; // Size: 4, Type: float
			constexpr auto Stars Speed = 0x420; // Size: 4, Type: float
			constexpr auto Sun Inclination = 0x424; // Size: 4, Type: float
			constexpr auto Sun Yaw = 0x428; // Size: 4, Type: float
			constexpr auto Moon Rotation = 0x42c; // Size: 4, Type: float
			constexpr auto Custom Moon Texture = 0x430; // Size: 8, Type: struct UTexture2D*
			constexpr auto Use Custom Moon Texture = 0x438; // Size: 1, Type: bool
			constexpr auto SkyLight = 0x440; // Size: 8, Type: struct ASkyLight*
			constexpr auto Recapture Sky light periodically = 0x448; // Size: 1, Type: bool
			constexpr auto Sky Light recapture period = 0x44c; // Size: 4, Type: float
			constexpr auto Night Filter Curve = 0x450; // Size: 8, Type: struct UCurveFloat*
			constexpr auto Night brightness = 0x458; // Size: 4, Type: float
			constexpr auto Moon Glow Intensity = 0x45c; // Size: 4, Type: float
			constexpr auto Directional_Intensity_Curve = 0x460; // Size: 8, Type: struct UCurveFloat*
			constexpr auto Sun_Light_Intensity = 0x468; // Size: 4, Type: float
			constexpr auto Aurora Intensity = 0x46c; // Size: 4, Type: float
			constexpr auto Aurora Speed = 0x470; // Size: 4, Type: float
			constexpr auto Use Fast Skylight = 0x474; // Size: 1, Type: bool
			constexpr auto Use Auroras = 0x475; // Size: 1, Type: bool
			constexpr auto Clouds Base Texture = 0x478; // Size: 8, Type: struct UTexture*
			constexpr auto Cloud Tiling = 0x480; // Size: 4, Type: float
			constexpr auto Cloud Direction = 0x484; // Size: 4, Type: float
			constexpr auto One cloud layer = 0x488; // Size: 1, Type: bool
			constexpr auto Cloud Height 1 = 0x48c; // Size: 4, Type: float
			constexpr auto Cloud Height 2 = 0x490; // Size: 4, Type: float
			constexpr auto color_scheme = 0x494; // Size: 4, Type: int32_t
			constexpr auto Moon mat = 0x498; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto Moon Angle = 0x4a0; // Size: 4, Type: float
			constexpr auto Sun_Volumetric_Scattering_Intensity = 0x4a4; // Size: 4, Type: float
			constexpr auto Moon_Volumetric_Scattering_Intensity = 0x4a8; // Size: 4, Type: float
			constexpr auto color_scheme_new = 0x4ac; // Size: 4, Type: int32_t
			constexpr auto alpha_color_scheme = 0x4b0; // Size: 4, Type: float
			constexpr auto WeatherSchemes = 0x4b8; // Size: 80, Type: struct TMap<enum class EWTLWeatherType, struct FST_WeatherScheme>
			constexpr auto CurrentWeatherScheme = 0x508; // Size: 1, Type: enum class EWTLWeatherType
			constexpr auto TransitionWeatherScheme = 0x509; // Size: 1, Type: enum class EWTLWeatherType
			constexpr auto bIsRainParticlesEnabledOnThisLocation = 0x50a; // Size: 1, Type: bool
			constexpr auto UseStaticSunHighlightRadius = 0x50b; // Size: 1, Type: bool
			constexpr auto StaticSunHighlightRadius = 0x50c; // Size: 4, Type: float
			constexpr auto oldFog = 0x510; // Size: 1, Type: bool
			constexpr auto TimeOfDay(0-1) = 0x514; // Size: 4, Type: float
	}
} 
