namespace offsets
{
	namespace AWTLNPCActor
	{
			constexpr auto ID = 0x3a0; // Size: 4, Type: int32_t
			constexpr auto Name = 0x3a8; // Size: 24, Type: struct FText
			constexpr auto NPCType = 0x3c0; // Size: 1, Type: enum class EWTLNPCType
			constexpr auto NPCFaction = 0x3c1; // Size: 1, Type: enum class EWTLFaction
			constexpr auto DealWithNeutrals = 0x3c2; // Size: 1, Type: bool
			constexpr auto CanUseFactionClothes = 0x3c3; // Size: 1, Type: bool
			constexpr auto FactionClothesMap = 0x3c8; // Size: 80, Type: struct TMap<enum class EWTLFaction, struct FWTLNPCFactionClothesInfo>
			constexpr auto m_IsActive = 0x418; // Size: 1, Type: bool
			constexpr auto Capsule = 0x420; // Size: 8, Type: struct UCapsuleComponent*
			constexpr auto Mesh = 0x428; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshHead = 0x430; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshTorso = 0x438; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshLegs = 0x440; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshFeet = 0x448; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshHeadSlot = 0x450; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshTorsoSlot = 0x458; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshLegsSlot = 0x460; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshFeetSlot = 0x468; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshBackpackSlot = 0x470; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshGlassesSlot = 0x478; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto FrightSphereComponent = 0x480; // Size: 8, Type: struct USphereComponent*
			constexpr auto ReplicaAudio = 0x488; // Size: 8, Type: struct UAudioComponent*
			constexpr auto ReplicaAudioComponent = 0x490; // Size: 8, Type: struct UFMODAudioComponent*
			constexpr auto ReplicaTable = 0x498; // Size: 8, Type: struct UDataTable*
			constexpr auto CommonReplicaTable = 0x4a0; // Size: 8, Type: struct UDataTable*
			constexpr auto QuestArray = 0x4a8; // Size: 16, Type: struct TArray<struct FWTLQuestInfo>
			constexpr auto QuestReplicaArray = 0x4b8; // Size: 16, Type: struct TArray<struct FWTLQuestReplicas>
			constexpr auto PlayRandomIdleAnim = 0x4c8; // Size: 1, Type: bool
			constexpr auto AnimList = 0x4d0; // Size: 16, Type: struct TArray<struct FWTLNPCAnimationInfo>
			constexpr auto GreetingAnimationAlpha = 0x4e8; // Size: 4, Type: float
			constexpr auto GreetingAnimationIncrementRate = 0x4ec; // Size: 4, Type: float
			constexpr auto GreetingAnimationDecrementRate = 0x4f0; // Size: 4, Type: float
			constexpr auto GreetingAudio = 0x4f8; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto GoodByeAudio = 0x520; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto PhysicsAssetOverride = 0x548; // Size: 40, Type: struct TSoftObjectPtr<UPhysicsAsset>
			constexpr auto bShowOnMap = 0x618; // Size: 1, Type: bool
			constexpr auto bCanBuyItems = 0x619; // Size: 1, Type: bool
			constexpr auto BuyBasePriceMultiplier = 0x61c; // Size: 4, Type: float
			constexpr auto bCanBuyWeaponItems = 0x620; // Size: 1, Type: bool
			constexpr auto BuyOnlyWeaponItems = 0x628; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto BuyExceptWeaponItems = 0x638; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bCanBuyAmmoItems = 0x648; // Size: 1, Type: bool
			constexpr auto BuyOnlyAmmoItems = 0x650; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto BuyExceptAmmoItems = 0x660; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bCanBuyMedicineItems = 0x670; // Size: 1, Type: bool
			constexpr auto BuyOnlyMedicineItems = 0x678; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto BuyExceptMedicineItems = 0x688; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bCanBuyStuffItems = 0x698; // Size: 1, Type: bool
			constexpr auto BuyOnlyStuffItems = 0x6a0; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto BuyExceptStuffItems = 0x6b0; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bCanBuyClothesItems = 0x6c0; // Size: 1, Type: bool
			constexpr auto BuyOnlyClothesItems = 0x6c8; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto BuyExceptClothesItems = 0x6d8; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bCanBuyResourceItems = 0x6e8; // Size: 1, Type: bool
			constexpr auto BuyOnlyResourceItems = 0x6f0; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto BuyExceptResourceItems = 0x700; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bCanBuyArtefactItems = 0x710; // Size: 1, Type: bool
			constexpr auto BuyOnlyArtefactItems = 0x718; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto BuyExceptArtefactItems = 0x728; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto CanBuyStrangeArtefactItems = 0x738; // Size: 1, Type: bool
			constexpr auto bCanSellItems = 0x739; // Size: 1, Type: bool
			constexpr auto SellBasePriceMultiplier = 0x73c; // Size: 4, Type: float
			constexpr auto GenerateSellItemsTimerInterval = 0x740; // Size: 4, Type: float
			constexpr auto GeneratedSellItems = 0x748; // Size: 16, Type: struct TArray<struct FWTLGeneratedSellItemInfo>
			constexpr auto SellItems = 0x758; // Size: 112, Type: struct FWTLSellItems
			constexpr auto SellItemsQuestRestrictions = 0x7c8; // Size: 16, Type: struct TArray<struct FWTLSellItemsQuestRestrictions>
			constexpr auto CommissionSellItems = 0x7d8; // Size: 112, Type: struct FWTLSellItems
			constexpr auto ExpiredCommissionSellItems = 0x848; // Size: 112, Type: struct FWTLSellItems
			constexpr auto CommissionSellItemsPageCount = 0x8b8; // Size: 4, Type: int32_t
			constexpr auto CommissionSellItemsPerPage = 0x8bc; // Size: 4, Type: int32_t
			constexpr auto CommissionSellItemsCount = 0x8c0; // Size: 4, Type: int32_t
			constexpr auto CommissionSellItemsPageIndex = 0x8c4; // Size: 4, Type: int32_t
			constexpr auto CommissionSellItemsTypesCount = 0x8c8; // Size: 80, Type: struct TMap<enum class EWTLItemType, int32_t>
			constexpr auto CommissionSellItemsPage = 0x918; // Size: 112, Type: struct FWTLSellItems
			constexpr auto bCanGetCommissionItems = 0x988; // Size: 1, Type: bool
			constexpr auto bCanGetWeaponCommissionItems = 0x989; // Size: 1, Type: bool
			constexpr auto bCanGetAmmoCommissionItems = 0x98a; // Size: 1, Type: bool
			constexpr auto bCanGetMedicineCommissionItems = 0x98b; // Size: 1, Type: bool
			constexpr auto bCanGetStuffCommissionItems = 0x98c; // Size: 1, Type: bool
			constexpr auto bCanGetClothesCommissionItems = 0x98d; // Size: 1, Type: bool
			constexpr auto bCanGetResourceCommissionItems = 0x98e; // Size: 1, Type: bool
			constexpr auto bCanGetArtefactCommissionItems = 0x98f; // Size: 1, Type: bool
			constexpr auto CommissionPercent = 0x990; // Size: 4, Type: float
			constexpr auto CommissionMinItemPrice = 0x994; // Size: 4, Type: float
			constexpr auto CommissionDayPrice = 0x998; // Size: 4, Type: float
			constexpr auto CommissionMaxDaysCount = 0x99c; // Size: 4, Type: int32_t
			constexpr auto CommissionMaxItemCount = 0x9a0; // Size: 4, Type: int32_t
			constexpr auto Supply = 0x9a8; // Size: 16, Type: struct TArray<struct FWTLNPCSupply>
			constexpr auto SupplyListReplicaArray = 0x9b8; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto SupplyBuyReplicaArray = 0x9c8; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto SupplyReturnReplicaID = 0x9d8; // Size: 4, Type: int32_t
			constexpr auto MaxSupplyExperience = 0x9dc; // Size: 4, Type: int32_t
			constexpr auto bHasPrivateStorage = 0x9e0; // Size: 1, Type: bool
			constexpr auto PrivateStoragePrice = 0x9e4; // Size: 4, Type: int32_t
			constexpr auto PrivateStorageSlotCount = 0x9e8; // Size: 1, Type: char
			constexpr auto MaxPrivateStorageSlotCount = 0x9e9; // Size: 1, Type: char
			constexpr auto PrivateStorageAdditionalSlotPrice = 0x9ec; // Size: 4, Type: int32_t
			constexpr auto PrivateStorageSlotWeight = 0x9f0; // Size: 4, Type: int32_t
			constexpr auto bHasClanStorage = 0x9f4; // Size: 1, Type: bool
			constexpr auto ClanStoragePrice = 0x9f8; // Size: 4, Type: int32_t
			constexpr auto ClanStorageTabSlots = 0x9fc; // Size: 1, Type: char
			constexpr auto ClanStorageTabCount = 0x9fd; // Size: 1, Type: char
			constexpr auto ClanStorageMaxTabCount = 0x9fe; // Size: 1, Type: char
			constexpr auto ClanStorageAdditionalTabPrice = 0xa00; // Size: 4, Type: int32_t
			constexpr auto ClanStorageAdditionalTabItemRequirements = 0xa08; // Size: 16, Type: struct TArray<struct FWTLItemRequirement>
			constexpr auto ClanStorageSlotWeight = 0xa18; // Size: 4, Type: int32_t
			constexpr auto ClanStorageItemsLogPageCount = 0xa1c; // Size: 4, Type: int32_t
			constexpr auto ClanStorageItemsLogRecordsPerPage = 0xa20; // Size: 4, Type: int32_t
			constexpr auto ClanStorageItemsLogRecordCount = 0xa24; // Size: 4, Type: int32_t
			constexpr auto ClanStorageItemsLogPageIndex = 0xa28; // Size: 4, Type: int32_t
			constexpr auto ClanStorageItemsLogPage = 0xa30; // Size: 16, Type: struct TArray<struct FWTLClanStorageItemLogRecord>
			constexpr auto ClanStorageMoneyLogPageCount = 0xa40; // Size: 4, Type: int32_t
			constexpr auto ClanStorageMoneyLogRecordsPerPage = 0xa44; // Size: 4, Type: int32_t
			constexpr auto ClanStorageMoneyLogRecordCount = 0xa48; // Size: 4, Type: int32_t
			constexpr auto ClanStorageMoneyLogPageIndex = 0xa4c; // Size: 4, Type: int32_t
			constexpr auto ClanStorageMoneyLogPage = 0xa50; // Size: 16, Type: struct TArray<struct FWTLClanStorageMoneyLogRecord>
			constexpr auto bCanRepairItems = 0xa60; // Size: 1, Type: bool
			constexpr auto bCanRepairWeapon = 0xa61; // Size: 1, Type: bool
			constexpr auto MinWeaponConditionToRepair = 0xa64; // Size: 4, Type: int32_t
			constexpr auto bCanRepairStuff = 0xa68; // Size: 1, Type: bool
			constexpr auto MinStuffConditionToRepair = 0xa6c; // Size: 4, Type: int32_t
			constexpr auto bCanRepairClothes = 0xa70; // Size: 1, Type: bool
			constexpr auto MinClothesConditionToRepair = 0xa74; // Size: 4, Type: int32_t
			constexpr auto RepairExperience = 0xa78; // Size: 4, Type: int32_t
			constexpr auto RepairPriceMultiplier = 0xa7c; // Size: 4, Type: float
			constexpr auto IdleAnimations = 0xa80; // Size: 16, Type: struct TArray<struct FWTLNPCIdleAnimation>
			constexpr auto IdleAnimationSlotName = 0xa90; // Size: 8, Type: struct FName
			constexpr auto LookAtTargetPlayer = 0xa98; // Size: 1, Type: bool
			constexpr auto CharacterReplicaArrayMainDialog = 0xaa0; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto CharacterReplicaArrayEndDialog = 0xab0; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto CharacterReplicaArrayReMainDialog = 0xac0; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto NPCReplicaArrayHaveJob = 0xad0; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bCanCustomizeItems = 0xae0; // Size: 1, Type: bool
			constexpr auto CustomizationScalarPrice = 0xae4; // Size: 4, Type: float
			constexpr auto CustomizationColorPrice = 0xae8; // Size: 4, Type: float
			constexpr auto IndexAnimIdle = 0xaf8; // Size: 1, Type: char
			constexpr auto HeadRotationSpeed = 0xafc; // Size: 4, Type: float
	}
} 
