namespace offsets
{
	namespace AWTLPlayerState
	{
			constexpr auto m_MailPackageCount = 0x340; // Size: 4, Type: int32_t
			constexpr auto m_PlacedMinesCount = 0x344; // Size: 1, Type: char
			constexpr auto m_PlacedStickyMinesCount = 0x345; // Size: 1, Type: char
			constexpr auto m_IsPieceOfShit = 0x346; // Size: 1, Type: bool
			constexpr auto m_PlayerPawnType = 0x3d0; // Size: 1, Type: enum class EWTLPlayerPawnType
			constexpr auto m_CharacterInfo = 0x420; // Size: 272, Type: struct FWTLCharacterInfo
			constexpr auto m_CharacterCurrentState_Health = 0x6b8; // Size: 4, Type: float
			constexpr auto m_CharacterCurrentState_Strength = 0x6bc; // Size: 1, Type: char
			constexpr auto m_CharacterCurrentState_Dexterity = 0x6bd; // Size: 1, Type: char
			constexpr auto m_CharacterCurrentState_Stamina = 0x6be; // Size: 1, Type: char
			constexpr auto m_CharacterCurrentState_Accuracy = 0x6bf; // Size: 1, Type: char
			constexpr auto m_CharacterCurrentState_Intelligence = 0x6c0; // Size: 1, Type: char
			constexpr auto m_CharacterCurrentState_Fortune = 0x6c1; // Size: 1, Type: char
			constexpr auto m_CharacterCurrentState_LocationID = 0x6c4; // Size: 4, Type: uint32_t
			constexpr auto m_CharacterCurrentState_LocationPosition = 0x6c8; // Size: 12, Type: struct FVector
			constexpr auto m_CharacterCurrentState_ArmsItemType = 0x6d4; // Size: 1, Type: enum class EWTLItemType
			constexpr auto m_CharacterCurrentState_ArmsItemID = 0x6d8; // Size: 8, Type: uint64_t
			constexpr auto m_CharacterCurrentState_HeadItemType = 0x6e0; // Size: 1, Type: enum class EWTLItemType
			constexpr auto m_CharacterCurrentState_HeadItemID = 0x6e8; // Size: 8, Type: uint64_t
			constexpr auto m_CharacterCurrentState_TorsoItemType = 0x6f0; // Size: 1, Type: enum class EWTLItemType
			constexpr auto m_CharacterCurrentState_TorsoItemID = 0x6f8; // Size: 8, Type: uint64_t
			constexpr auto m_CharacterCurrentState_LegsItemType = 0x700; // Size: 1, Type: enum class EWTLItemType
			constexpr auto m_CharacterCurrentState_LegsItemID = 0x708; // Size: 8, Type: uint64_t
			constexpr auto m_CharacterCurrentState_FeetItemType = 0x710; // Size: 1, Type: enum class EWTLItemType
			constexpr auto m_CharacterCurrentState_FeetItemID = 0x718; // Size: 8, Type: uint64_t
			constexpr auto m_CharacterCurrentState_EquipmentSlot1ItemType = 0x720; // Size: 1, Type: enum class EWTLItemType
			constexpr auto m_CharacterCurrentState_EquipmentSlot1ItemID = 0x728; // Size: 8, Type: uint64_t
			constexpr auto m_CharacterCurrentState_EquipmentSlot2ItemType = 0x730; // Size: 1, Type: enum class EWTLItemType
			constexpr auto m_CharacterCurrentState_EquipmentSlot2ItemID = 0x738; // Size: 8, Type: uint64_t
			constexpr auto m_CharacterCurrentState_EquipmentSlot3ItemType = 0x740; // Size: 1, Type: enum class EWTLItemType
			constexpr auto m_CharacterCurrentState_EquipmentSlot3ItemID = 0x748; // Size: 8, Type: uint64_t
			constexpr auto m_CharacterCurrentState_EquipmentSlot4ItemType = 0x750; // Size: 1, Type: enum class EWTLItemType
			constexpr auto m_CharacterCurrentState_EquipmentSlot4ItemID = 0x758; // Size: 8, Type: uint64_t
			constexpr auto m_CharacterCurrentState_EquipmentSlotStates = 0x760; // Size: 1, Type: char
			constexpr auto m_CharacterCurrentState_FastAccessSlots = 0x768; // Size: 16, Type: struct TArray<struct FWTLFastAccessSlot>
			constexpr auto m_CharacterCurrentState_SafeZoneID = 0x778; // Size: 4, Type: int32_t
			constexpr auto m_CharacterCurrentState_VisitedLocations = 0x780; // Size: 16, Type: struct TArray<struct FWTLIdentity32>
			constexpr auto m_CharacterCurrentState_PDAModules = 0x790; // Size: 16, Type: struct TArray<struct FWTLIdentity16>
			constexpr auto m_CharacterCurrentState_VisitedPortals = 0x7a0; // Size: 16, Type: struct TArray<struct FWTLIdentity32>
			constexpr auto m_CharacterCurrentState_Hunger = 0x7b0; // Size: 1, Type: char
			constexpr auto m_CharacterCurrentState_Thirst = 0x7b1; // Size: 1, Type: char
			constexpr auto m_CharacterCurrentState_MedicineEffect = 0x7b8; // Size: 48, Type: struct FWTLMedicineItemEffect
			constexpr auto m_CharacterCurrentState_StimulatorEffect = 0x7e8; // Size: 48, Type: struct FWTLMedicineItemEffect
			constexpr auto m_CharacterItemExperience = 0x818; // Size: 280, Type: struct FWTLCharacterItemExperienceFastArray
			constexpr auto m_CharacterContactList = 0x9d8; // Size: 16, Type: struct TArray<struct FWTLContactListItem>
			constexpr auto m_CharacterSkills = 0x9e8; // Size: 16, Type: struct TArray<struct FWTLIdentity16>
			constexpr auto m_CharacterParameters = 0x9f8; // Size: 224, Type: struct FWTLCharacterParameters
			constexpr auto m_CharacterCustomizationInfo = 0xad8; // Size: 16, Type: struct TArray<struct FWTLCharacterCustomizationRecord>
			constexpr auto m_CharacterMapMarkers = 0xaf8; // Size: 280, Type: struct FWTLCharacterMapMarkerArray
			constexpr auto m_CharacterEffects = 0xc10; // Size: 280, Type: struct FWTLCharacterEffectArray
			constexpr auto m_CharacterMail = 0xd28; // Size: 16, Type: struct TArray<struct FWTLCharacterMailMessage>
			constexpr auto m_ShortCharacterInfo_ID = 0xf70; // Size: 8, Type: uint64_t
			constexpr auto m_ShortCharacterInfo_Sex = 0xf78; // Size: 1, Type: enum class EWTLSex
			constexpr auto m_ShortCharacterInfo_Level = 0xf79; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_Class = 0xf7a; // Size: 1, Type: enum class EWTLCharacterClass
			constexpr auto m_ShortCharacterInfo_Health = 0xf7c; // Size: 4, Type: float
			constexpr auto m_ShortCharacterInfo_ReadyToGame = 0xf80; // Size: 1, Type: bool
			constexpr auto m_ShortCharacterInfo_Strength = 0xf81; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_Dexterity = 0xf82; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_Stamina = 0xf83; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_Accuracy = 0xf84; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_Intelligence = 0xf85; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_Fortune = 0xf86; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_HeadItem = 0xf88; // Size: 48, Type: struct FWTLCharacterSlotItemInfo
			constexpr auto m_ShortCharacterInfo_TorsoItem = 0xfb8; // Size: 48, Type: struct FWTLCharacterSlotItemInfo
			constexpr auto m_ShortCharacterInfo_LegsItem = 0xfe8; // Size: 48, Type: struct FWTLCharacterSlotItemInfo
			constexpr auto m_ShortCharacterInfo_FeetItem = 0x1018; // Size: 48, Type: struct FWTLCharacterSlotItemInfo
			constexpr auto m_ShortCharacterInfo_ArmsItem = 0x1048; // Size: 48, Type: struct FWTLCharacterSlotItemInfo
			constexpr auto m_ShortCharacterInfo_FastAccessSlots = 0x1078; // Size: 280, Type: struct FWTLFastAccessSlotItemInfoArray
			constexpr auto m_ShortCharacterInfo_Faction = 0x1190; // Size: 1, Type: enum class EWTLFaction
			constexpr auto m_ShortCharacterInfo_Reputation = 0x1191; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_Rank = 0x1192; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_ClanID = 0x1194; // Size: 2, Type: uint16_t
			constexpr auto m_ShortCharacterInfo_ClanMemberType = 0x1196; // Size: 1, Type: enum class EWTLClanMemberType
			constexpr auto m_ShortCharacterInfo_PlayerType = 0x1197; // Size: 1, Type: enum class EWTLPlayerType
			constexpr auto m_ShortCharacterInfo_BodyType = 0x1198; // Size: 1, Type: char
			constexpr auto m_ShortCharacterInfo_PVPEnabled = 0x1199; // Size: 1, Type: bool
			constexpr auto m_ShortCharacterInfo_CustomizationInfo = 0x11a0; // Size: 16, Type: struct TArray<struct FWTLCharacterCustomizationPackedRecord>
			constexpr auto m_ShortCharacterInfo_EquipmentSlot1 = 0x11b0; // Size: 48, Type: struct FWTLCharacterEquipmentItemInfo
			constexpr auto m_ShortCharacterInfo_EquipmentSlot2 = 0x11e0; // Size: 48, Type: struct FWTLCharacterEquipmentItemInfo
			constexpr auto m_ShortCharacterInfo_EquipmentSlot3 = 0x1210; // Size: 48, Type: struct FWTLCharacterEquipmentItemInfo
			constexpr auto m_ShortCharacterInfo_EquipmentSlot4 = 0x1240; // Size: 48, Type: struct FWTLCharacterEquipmentItemInfo
			constexpr auto m_ShortCharacterInfo_EquipmentSlotStates = 0x1270; // Size: 1, Type: char
			constexpr auto m_InventoryWeight = 0x1274; // Size: 4, Type: uint32_t
			constexpr auto m_MaxInventoryWeight = 0x1278; // Size: 4, Type: uint32_t
			constexpr auto m_MaxHealth = 0x127c; // Size: 4, Type: float
			constexpr auto m_MuteStateChat = 0x1280; // Size: 1, Type: bool
			constexpr auto m_MuteStateVoice = 0x1281; // Size: 1, Type: bool
			constexpr auto m_MuteStateMuteEnd = 0x1288; // Size: 8, Type: struct FWTLDateTime
			constexpr auto m_MuteStateDescription = 0x1290; // Size: 16, Type: struct FString
			constexpr auto m_IsFounder = 0x12a0; // Size: 1, Type: bool
			constexpr auto m_ClanMembers = 0x12c8; // Size: 16, Type: struct TArray<struct FWTLClanMember>
			constexpr auto m_ClanPolicyGroups = 0x12d8; // Size: 16, Type: struct TArray<struct FWTLClanPolicyGroup>
			constexpr auto m_CommissionStorages = 0x12e8; // Size: 16, Type: struct TArray<struct FWTLCommissionStorage>
			constexpr auto m_CraftObjectStates = 0x12f8; // Size: 16, Type: struct TArray<struct FWTLCraftObjectState>
			constexpr auto m_BarterDeal = 0x1308; // Size: 384, Type: struct FWTLBarterDeal
			constexpr auto m_MailStorage = 0x1488; // Size: 168, Type: struct FWTLStorageContent
			constexpr auto m_LastOperationResult = 0x1530; // Size: 32, Type: struct FWTLOperationResult
			constexpr auto m_CanPlaceCampfire = 0x1550; // Size: 1, Type: bool
			constexpr auto m_CanPlaceStash = 0x1551; // Size: 1, Type: bool
			constexpr auto m_LastCampfireLocation = 0x1554; // Size: 12, Type: struct FVector
			constexpr auto m_LastStashLocation = 0x1560; // Size: 12, Type: struct FVector
			constexpr auto Group = 0x1690; // Size: 80, Type: struct FWTLGroup
			constexpr auto StimulatorEffects = 0x16e0; // Size: 16, Type: struct TArray<struct FWTLStimulatorEffect>
			constexpr auto LastDeathFromCharacterID = 0x16f0; // Size: 8, Type: uint64_t
			constexpr auto bIsPVPAllowed = 0x16f8; // Size: 1, Type: bool
			constexpr auto SteamID = 0x1700; // Size: 8, Type: uint64_t
			constexpr auto m_SavedTeleportationDeviceItemID = 0x1808; // Size: 8, Type: uint64_t
	}
} 
