namespace offsets
{
	namespace AWTLRangedWeapon
	{
			constexpr auto m_CurrentState = 0x3d8; // Size: 1, Type: enum class EWTLWeaponState
			constexpr auto m_CurrentFireModeIndex = 0x3e8; // Size: 4, Type: int32_t
			constexpr auto m_InterruptLoadingReceived = 0x484; // Size: 1, Type: bool
			constexpr auto m_MuzzleAttachmentTypeID = 0x588; // Size: 2, Type: uint16_t
			constexpr auto m_FlashlightAttachmentTypeID = 0x58a; // Size: 2, Type: uint16_t
			constexpr auto m_ScopeAttachmentTypeID = 0x58c; // Size: 2, Type: uint16_t
			constexpr auto m_CustomizationScalar = 0x58e; // Size: 1, Type: char
			constexpr auto m_CustomizationColor = 0x58f; // Size: 1, Type: char
			constexpr auto m_CurrentAmmoID = 0x590; // Size: 2, Type: uint16_t
			constexpr auto m_HandlingAnimationType = 0x592; // Size: 1, Type: char
			constexpr auto MuzzleAttachment = 0x5d8; // Size: 8, Type: struct UWTLWeaponAttachment*
			constexpr auto MuzzleMount = 0x5e0; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto FlashlightAttachment = 0x5e8; // Size: 8, Type: struct UWTLWeaponAttachment*
			constexpr auto FlashlightMount = 0x5f0; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto ScopeAttachment = 0x5f8; // Size: 8, Type: struct UWTLWeaponAttachment*
			constexpr auto ScopeMount = 0x600; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto AutomaticFireAudioComponent = 0x608; // Size: 8, Type: struct UFMODAudioComponent*
			constexpr auto AmmoCaseParticleComponent = 0x610; // Size: 8, Type: struct UParticleSystemComponent*
			constexpr auto ScopeFlareComponent = 0x618; // Size: 8, Type: struct UMaterialBillboardComponent*
			constexpr auto m_FlareMaterial = 0x620; // Size: 8, Type: struct UMaterialInterface*
			constexpr auto m_FlareIntensityDetectionCurve = 0x628; // Size: 8, Type: struct UCurveFloat*
			constexpr auto m_FlareMaterialInstance = 0x630; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto FireModes = 0x638; // Size: 16, Type: struct TArray<enum class EWTLFireMode>
			constexpr auto StandSpreadMultiplier = 0x648; // Size: 4, Type: float
			constexpr auto CrouchSpreadMultiplier = 0x64c; // Size: 4, Type: float
			constexpr auto ProneSpreadMultiplier = 0x650; // Size: 4, Type: float
			constexpr auto WalkSpreadMultiplier = 0x654; // Size: 4, Type: float
			constexpr auto SprintSpreadMultiplier = 0x658; // Size: 4, Type: float
			constexpr auto AimSpreadMultiplier = 0x65c; // Size: 4, Type: float
			constexpr auto CanInterruptLoading = 0x660; // Size: 1, Type: bool
			constexpr auto PreInstalledScopeStuffID = 0x664; // Size: 4, Type: int32_t
			constexpr auto PreInstalledMuzzleStuffID = 0x668; // Size: 4, Type: int32_t
			constexpr auto PreInstalledFlashlightStuffID = 0x66c; // Size: 4, Type: int32_t
			constexpr auto BaseRecoilTranslation = 0x670; // Size: 4, Type: float
			constexpr auto AdditionalRecoilTranslation = 0x674; // Size: 4, Type: float
			constexpr auto MinRecoilRotation = 0x678; // Size: 12, Type: struct FRotator
			constexpr auto MaxRecoilRotation = 0x684; // Size: 12, Type: struct FRotator
			constexpr auto RecoilTranslationInterpolateSpeed = 0x690; // Size: 4, Type: float
			constexpr auto RecoilRotationInterpolateSpeed = 0x694; // Size: 4, Type: float
			constexpr auto AimingRecoilTranslationInterpolateSpeed = 0x698; // Size: 4, Type: float
			constexpr auto AimingRecoilRotationInterpolateSpeed = 0x69c; // Size: 4, Type: float
			constexpr auto AimingRecoilMultiplier = 0x6a0; // Size: 4, Type: float
			constexpr auto CrouchRecoilMultiplier = 0x6a4; // Size: 4, Type: float
			constexpr auto ProneRecoilMultiplier = 0x6a8; // Size: 4, Type: float
			constexpr auto RecoilSafePauseBetweenUse = 0x6ac; // Size: 4, Type: float
			constexpr auto MaxRecoilAccuracyDelta = 0x6b0; // Size: 4, Type: float
			constexpr auto RecoilCameraShake = 0x6b8; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto RecoilCameraShakeScale = 0x6e0; // Size: 4, Type: float
			constexpr auto RecoilCurve = 0x6e8; // Size: 8, Type: struct UCurveVector*
			constexpr auto RecoilValueMultiplierMin = 0x6f0; // Size: 4, Type: float
			constexpr auto RecoilValueMultiplierMax = 0x6f4; // Size: 4, Type: float
			constexpr auto RecoilSpeedMultiplier = 0x6f8; // Size: 4, Type: float
			constexpr auto NeedToReplaceReloadMontage = 0x6fc; // Size: 1, Type: bool
			constexpr auto CrosshairIsAlwaysHidden = 0x6fd; // Size: 1, Type: bool
			constexpr auto AdditionalSpawnRotation = 0x700; // Size: 12, Type: struct FRotator
			constexpr auto FireSequenceSet = 0x728; // Size: 24, Type: struct FItemAnimationSet
			constexpr auto LastFireSequenceSet = 0x740; // Size: 24, Type: struct FItemAnimationSet
			constexpr auto ReloadSequenceSet = 0x758; // Size: 24, Type: struct FItemAnimationSet
			constexpr auto ProReloadSequenceSet = 0x770; // Size: 24, Type: struct FItemAnimationSet
			constexpr auto LoadSequenceSet = 0x788; // Size: 24, Type: struct FItemAnimationSet
			constexpr auto ProLoadSequenceSet = 0x7a0; // Size: 24, Type: struct FItemAnimationSet
			constexpr auto NormalFireSoundEvent = 0x7b8; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto NormalFireSoundNoiseRadius = 0x7e0; // Size: 4, Type: float
			constexpr auto NormalFireSoundNoiseLoudness = 0x7e4; // Size: 4, Type: float
			constexpr auto NormalFireSoundNoiseName = 0x7e8; // Size: 8, Type: struct FName
			constexpr auto NormalFireParticles = 0x7f0; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto NormalFireParticlesScale = 0x818; // Size: 12, Type: struct FVector
			constexpr auto MuzzleBrakeFireSoundEvent = 0x828; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto MuzzleBrakeFireSoundNoiseRadius = 0x850; // Size: 4, Type: float
			constexpr auto MuzzleBrakeFireSoundNoiseLoudness = 0x854; // Size: 4, Type: float
			constexpr auto MuzzleBrakeFireSoundNoiseName = 0x858; // Size: 8, Type: struct FName
			constexpr auto MuzzleBrakeFireParticles = 0x860; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto MuzzleBrakeFireParticlesScale = 0x888; // Size: 12, Type: struct FVector
			constexpr auto SilencerFireSoundEvent = 0x898; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto LastShotsAdditionalSoundEvent = 0x8c0; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto SilencerFireSoundNoiseRadius = 0x8e8; // Size: 4, Type: float
			constexpr auto SilencerFireSoundNoiseLoudness = 0x8ec; // Size: 4, Type: float
			constexpr auto SilencerFireSoundNoiseName = 0x8f0; // Size: 8, Type: struct FName
			constexpr auto SilencerFireParticles = 0x8f8; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto SilencerFireParticlesScale = 0x920; // Size: 12, Type: struct FVector
			constexpr auto DryFireSoundEvent = 0x930; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto AutomaticFireSoundEvent = 0x958; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto AimingFOV = 0x980; // Size: 4, Type: float
			constexpr auto AimingTurnRateMultiplier = 0x984; // Size: 4, Type: float
			constexpr auto AimingLookUpRateMultiplier = 0x988; // Size: 4, Type: float
			constexpr auto NormalIdentificationTraceRange = 0x98c; // Size: 4, Type: float
			constexpr auto AimingIdentificationTraceRange = 0x990; // Size: 4, Type: float
			constexpr auto MaxVerticalHandsShaking = 0x994; // Size: 4, Type: float
			constexpr auto MaxHorizontalHandsShaking = 0x998; // Size: 4, Type: float
			constexpr auto HandsShakingSpeed = 0x99c; // Size: 4, Type: float
			constexpr auto VingettePerShootAmount = 0x9a0; // Size: 4, Type: float
			constexpr auto VingetteLimit = 0x9a4; // Size: 4, Type: float
			constexpr auto NormalCameraOffsetMale = 0x9a8; // Size: 12, Type: struct FVector
			constexpr auto AimingCameraOffsetMale = 0x9b4; // Size: 12, Type: struct FVector
			constexpr auto NormalCameraOffsetFemale = 0x9c0; // Size: 12, Type: struct FVector
			constexpr auto AimingCameraOffsetFemale = 0x9cc; // Size: 12, Type: struct FVector
			constexpr auto AimingHandsTranslationMale = 0x9d8; // Size: 12, Type: struct FVector
			constexpr auto AimingHandsTranslationFemale = 0x9e4; // Size: 12, Type: struct FVector
			constexpr auto UseOnlyFullReloading = 0x9f0; // Size: 1, Type: bool
	}
} 
