namespace offsets
{
	namespace AWTLCharacter
	{
			constexpr auto bIsMovementEnabled = 0x530; // Size: 1, Type: bool
			constexpr auto m_ReplicatedStamina = 0x550; // Size: 4, Type: float
			constexpr auto m_ReplicatedOxygen = 0x558; // Size: 4, Type: float
			constexpr auto m_FlashlightEnabled = 0x618; // Size: 1, Type: bool
			constexpr auto m_IsInvulnerable = 0x619; // Size: 1, Type: bool
			constexpr auto m_IsInSafeZone = 0x61a; // Size: 1, Type: bool
			constexpr auto m_CanSpawnOnSafeZone = 0x61b; // Size: 1, Type: bool
			constexpr auto m_IsInMobileResurectionPointWorkZone = 0x61c; // Size: 1, Type: bool
			constexpr auto m_IsInPVPZone = 0x61d; // Size: 1, Type: bool
			constexpr auto m_IsTraveling = 0x61e; // Size: 1, Type: bool
			constexpr auto m_LastEventPoint = 0x680; // Size: 8, Type: struct AWTLEventPoint*
			constexpr auto m_AdminSprintMode = 0x688; // Size: 1, Type: bool
			constexpr auto m_IsHoldingBreath = 0x6b8; // Size: 1, Type: bool
			constexpr auto m_AgressorFlag = 0x6d8; // Size: 1, Type: bool
			constexpr auto bIsInFishingZone = 0x6f0; // Size: 1, Type: bool
			constexpr auto bIsPlacingItem = 0x6f1; // Size: 1, Type: bool
			constexpr auto m_bIsInQuickThrowingState = 0x6f3; // Size: 1, Type: bool
			constexpr auto m_CurrentRadiationLevel = 0x718; // Size: 4, Type: float
			constexpr auto m_SpeedModifiers = 0x7d8; // Size: 8, Type: struct FSpeedModifiers
			constexpr auto ScopeOccluderDelta = 0x7e0; // Size: 4, Type: float
			constexpr auto MonocularOccluderDelta = 0x7e4; // Size: 4, Type: float
			constexpr auto DeathBreathSoundEvent = 0x7e8; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto StartHoldingBreathSoundEvent = 0x810; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto StopHoldingBreathSoundEvent = 0x838; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto TeleportSoundEvent = 0x860; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto HearingDamageEvent = 0x888; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto DrunkSoundMix = 0x8b0; // Size: 40, Type: struct TSoftObjectPtr<USoundMix>
			constexpr auto WalkFootstepMinInterval = 0x8d8; // Size: 4, Type: float
			constexpr auto WalkFootstepVolume = 0x8dc; // Size: 4, Type: float
			constexpr auto SprintFootstepMinInterval = 0x8e0; // Size: 4, Type: float
			constexpr auto SprintFootstepVolume = 0x8e4; // Size: 4, Type: float
			constexpr auto CrouchFootstepMinInterval = 0x8e8; // Size: 4, Type: float
			constexpr auto CrouchFootstepVolume = 0x8ec; // Size: 4, Type: float
			constexpr auto AimFootstepVolumeMultiplier = 0x8f0; // Size: 4, Type: float
			constexpr auto MeshTorso = 0x900; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshLegs = 0x908; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshFeet = 0x910; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshHead = 0x918; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshNeck = 0x920; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshHeadSlot = 0x928; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshTorsoSlot = 0x930; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshLegsSlot = 0x938; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto MeshFeetSlot = 0x940; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto BackpackSlot = 0x948; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto GlassesSlot = 0x950; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto WatchesSlot = 0x958; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto EquipmentSlot1 = 0x960; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto EquipmentSlot2 = 0x968; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto EquipmentSlot3 = 0x970; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto EquipmentSlot4 = 0x978; // Size: 8, Type: struct USkeletalMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot0 = 0x980; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot0MuzzleMount = 0x988; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot0MuzzleAttachment = 0x990; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot0FlashlightMount = 0x998; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot0FlashlightAttachment = 0x9a0; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot0ScopeMount = 0x9a8; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot0ScopeAttachment = 0x9b0; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot1 = 0x9b8; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot1MuzzleMount = 0x9c0; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot1MuzzleAttachment = 0x9c8; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot1FlashlightMount = 0x9d0; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot1FlashlightAttachment = 0x9d8; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot1ScopeMount = 0x9e0; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedWeaponPreviewSlot1ScopeAttachment = 0x9e8; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedStuffPreviewSlot5 = 0x9f0; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto HolsterSlot = 0x9f8; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto EquippedPistolPreviewSlot = 0xa00; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto SheathSlot = 0xa08; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto SheathPreviewSlot = 0xa10; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto FlashlightComponent = 0xa18; // Size: 8, Type: struct UWTLFlashlightMountComponent*
			constexpr auto LightComponent = 0xa20; // Size: 8, Type: struct USpotLightComponent*
			constexpr auto FlashlightMesh = 0xa28; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto ScopeOccluderMesh = 0xa30; // Size: 8, Type: struct UStaticMeshComponent*
			constexpr auto BulletFlyNearVolume = 0xa38; // Size: 8, Type: struct USphereComponent*
			constexpr auto HeartbeatAudioComponent = 0xa40; // Size: 8, Type: struct UAudioComponent*
			constexpr auto CharacterVoiceComponent = 0xa48; // Size: 8, Type: struct UFMODAudioComponent*
			constexpr auto NDPDetectorAudioComponent = 0xa50; // Size: 8, Type: struct UFMODAudioComponent*
			constexpr auto RadiationDetectorAudioComponent = 0xa58; // Size: 8, Type: struct UFMODAudioComponent*
			constexpr auto VOIPComponent = 0xa60; // Size: 8, Type: struct UWTLFMODCharacterVoiceComponent*
			constexpr auto IdentityComponent = 0xa68; // Size: 8, Type: struct UWTLCharacterIdentityComponent*
			constexpr auto VOIPIndicatorSprite = 0xa70; // Size: 8, Type: struct UMaterialBillboardComponent*
			constexpr auto NoiseEmitterComponent = 0xa80; // Size: 8, Type: struct UPawnNoiseEmitterComponent*
			constexpr auto WidgetInteraction = 0xa88; // Size: 8, Type: struct UWidgetInteractionComponent*
			constexpr auto bIsDying = 0xa94; // Size: 1, Type: bool
			constexpr auto bIsAimToggle = 0xa95; // Size: 1, Type: bool
			constexpr auto bIsCrouchToggle = 0xa96; // Size: 1, Type: bool
			constexpr auto bIsSprintToggle = 0xa97; // Size: 1, Type: bool
			constexpr auto bAllowRebasing = 0xa98; // Size: 1, Type: bool
			constexpr auto RebasingDistance = 0xa9c; // Size: 4, Type: float
			constexpr auto LastTakeHitInfo = 0xaa0; // Size: 544, Type: struct FTakeHitInfo
			constexpr auto HandsState = 0xce1; // Size: 1, Type: enum class EWTLHandsState
			constexpr auto UsableItemInHands = 0xce8; // Size: 8, Type: struct AWTLUsable*
			constexpr auto QuickItemInHands = 0xcf0; // Size: 8, Type: struct AWTLUsable*
			constexpr auto bIsAiming = 0xcf8; // Size: 1, Type: bool
			constexpr auto bIsSprinting = 0xcf9; // Size: 1, Type: bool
			constexpr auto bIsJumping = 0xcfc; // Size: 1, Type: bool
			constexpr auto CurrentPose = 0xcfd; // Size: 1, Type: enum class EWTLCharacterPose
			constexpr auto SprintSpeed = 0xd00; // Size: 4, Type: float
			constexpr auto WalkSpeed = 0xd04; // Size: 4, Type: float
			constexpr auto CrouchSpeed = 0xd08; // Size: 4, Type: float
			constexpr auto ProneSpeed = 0xd0c; // Size: 4, Type: float
			constexpr auto SwimSpeed = 0xd10; // Size: 4, Type: float
			constexpr auto AimSpeedMultiplier = 0xd14; // Size: 4, Type: float
			constexpr auto MaxStamina = 0xd18; // Size: 4, Type: float
			constexpr auto StaminaNotMovingIncrement = 0xd1c; // Size: 4, Type: float
			constexpr auto StaminaMovingIncrement = 0xd20; // Size: 4, Type: float
			constexpr auto StaminaSprintDecrement = 0xd24; // Size: 4, Type: float
			constexpr auto StaminaPercentSprintAvailability = 0xd28; // Size: 4, Type: float
			constexpr auto StaminaJumpDecrementPercent = 0xd2c; // Size: 4, Type: float
			constexpr auto StaminaHoldingBreathDecrement = 0xd30; // Size: 4, Type: float
			constexpr auto StaminaWaterMovementDecrement = 0xd34; // Size: 4, Type: float
			constexpr auto StaminaUnderwaterDecrement = 0xd38; // Size: 4, Type: float
			constexpr auto MaxOxygen = 0xd3c; // Size: 4, Type: float
			constexpr auto OxygenNoBreatheDecrement = 0xd40; // Size: 4, Type: float
			constexpr auto OxygenBreatheIncrement = 0xd44; // Size: 4, Type: float
			constexpr auto StandMinPitchAngle = 0xd48; // Size: 4, Type: float
			constexpr auto StandMaxPitchAngle = 0xd4c; // Size: 4, Type: float
			constexpr auto CrouchMinPitchAngle = 0xd50; // Size: 4, Type: float
			constexpr auto CrouchMaxPitchAngle = 0xd54; // Size: 4, Type: float
			constexpr auto ProneMinPitchAngle = 0xd58; // Size: 4, Type: float
			constexpr auto ProneMaxPitchAngle = 0xd5c; // Size: 4, Type: float
			constexpr auto SwimMinPitchAngle = 0xd60; // Size: 4, Type: float
			constexpr auto SwimMaxPitchAngle = 0xd64; // Size: 4, Type: float
			constexpr auto GravityScaleInWater = 0xd68; // Size: 4, Type: float
			constexpr auto GravityScaleUnderWater = 0xd6c; // Size: 4, Type: float
			constexpr auto GravityScaleOnLand = 0xd70; // Size: 4, Type: float
			constexpr auto m_CameraOffsetInterpSpeed = 0xd8c; // Size: 4, Type: float
			constexpr auto m_InteractiveObjectInFocus = 0xf38; // Size: 8, Type: struct AActor*
			constexpr auto InterestObjectTypes = 0xf50; // Size: 16, Type: struct TArray<enum class EObjectTypeQuery>
			constexpr auto InterestTraceRadius = 0xf60; // Size: 4, Type: float
			constexpr auto bEnableHandsStateDebugging = 0xf88; // Size: 1, Type: bool
			constexpr auto m_bIsUnderWater = 0xfa8; // Size: 1, Type: bool
			constexpr auto m_bIsInWater = 0xfa9; // Size: 1, Type: bool
			constexpr auto m_bMovesOnWater = 0xfaa; // Size: 1, Type: bool
			constexpr auto m_CharacterEffectsTexture = 0xfb0; // Size: 40, Type: struct TSoftObjectPtr<UTexture2D>
			constexpr auto m_CharacterEffectIconsCoords = 0xfd8; // Size: 80, Type: struct TMap<enum class EWTLCharacterEffectType, struct FVector2D>
			constexpr auto m_CharacterIndicatorIconsCoords = 0x1028; // Size: 80, Type: struct TMap<enum class EWTLCharacterStateIndicatorType, struct FVector2D>
			constexpr auto Font = 0x1078; // Size: 40, Type: struct TSoftObjectPtr<UFont>
			constexpr auto DotPointerTexture = 0x10a0; // Size: 40, Type: struct TSoftObjectPtr<UTexture2D>
			constexpr auto m_DesiredTiltValue = 0x1124; // Size: 4, Type: float
			constexpr auto m_PlacementPreviewItemMaterial = 0x1128; // Size: 40, Type: struct TSoftObjectPtr<UMaterialInterface>
			constexpr auto m_RightPlacementColor = 0x1150; // Size: 16, Type: struct FLinearColor
			constexpr auto m_WrongPlacementColor = 0x1160; // Size: 16, Type: struct FLinearColor
			constexpr auto M_PlacementPointer = 0x1180; // Size: 8, Type: struct AStaticMeshActor*
			constexpr auto m_PlacementPreviewMaterialInstance = 0x1198; // Size: 8, Type: struct UMaterialInstanceDynamic*
			constexpr auto UndergroundFlashlightIntensityMultiplier = 0x11ac; // Size: 4, Type: float
			constexpr auto OtherCharacterFlashlightIntensityMultiplier = 0x11b0; // Size: 4, Type: float
			constexpr auto m_bIsFishing = 0x11d0; // Size: 1, Type: bool
			constexpr auto QTEState = 0x11d4; // Size: 16, Type: struct FWTLQTEState
			constexpr auto BlueprintSex = 0x1258; // Size: 1, Type: enum class EWTLSex
			constexpr auto m_CurrentActionGameplayActor = 0x12e0; // Size: 8, Type: struct AActor*
			constexpr auto m_CurrentEmotionKey = 0x12ea; // Size: 2, Type: uint16_t
			constexpr auto m_LeavingFromVehicle = 0x12f5; // Size: 1, Type: bool
			constexpr auto PersonalEnergyShieldState = 0x1319; // Size: 1, Type: bool
			constexpr auto m_Drone = 0x1328; // Size: 8, Type: struct AWTLDrone*
			constexpr auto m_DroneCameraDisplay = 0x1330; // Size: 8, Type: struct AWTLCameraDisplay*
			constexpr auto OnCharacterDestroy = 0x1338; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnTravelingResult = 0x1348; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCharacterDied = 0x1358; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCoreHackngResult = 0x1368; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCharacterLeavedFishingZone = 0x1378; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnCharacterEnteredInFishingZone = 0x1388; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnGameplayActionStarted = 0x1398; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto OnGameplayActionFinished = 0x13a8; // Size: 16, Type: struct FMulticastInlineDelegate
			constexpr auto m_bCanUseVehicleInAnomaly = 0x13b9; // Size: 1, Type: bool
			constexpr auto MaleAnimBlueprint = 0x13e0; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto MaleWatchesAnimBlueprint = 0x1408; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto FemaleAnimBlueprint = 0x1430; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto FemaleWatchesAnimBlueprint = 0x1458; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto StandLowerBodyRotation = 0x1480; // Size: 16, Type: struct FWTLLowerBodyAnimation
			constexpr auto CrouchLowerBodyRotation = 0x1490; // Size: 16, Type: struct FWTLLowerBodyAnimation
			constexpr auto MaleTimeCheckAnimationMontage = 0x14a0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto FemaleTimeCheckAnimationMontage = 0x14a8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto LadderUpStartMontage = 0x14b0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto LadderUpEndMontage = 0x14b8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto LadderDownStartMontage = 0x14c0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto LadderDownEndMontage = 0x14c8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto ThrowNutMontage = 0x14d0; // Size: 8, Type: struct UAnimMontage*
			constexpr auto PickItemMontage = 0x14d8; // Size: 8, Type: struct UAnimMontage*
			constexpr auto StunhitAnimations = 0x14e0; // Size: 80, Type: struct TMap<enum class EWTLCharacterStunhitDirection, struct UAnimMontage*>
			constexpr auto DrunkAnimationStunhitSet = 0x1530; // Size: 16, Type: struct TArray<enum class EWTLCharacterStunhitDirection>
			constexpr auto MaleNeckMesh = 0x1540; // Size: 40, Type: struct TSoftObjectPtr<USkeletalMesh>
			constexpr auto FemaleNeckMesh = 0x1568; // Size: 40, Type: struct TSoftObjectPtr<USkeletalMesh>
			constexpr auto MaleTorsoMeshFullArms = 0x1590; // Size: 40, Type: struct TSoftObjectPtr<USkeletalMesh>
			constexpr auto MaleTorsoMeshHalfArms = 0x15b8; // Size: 40, Type: struct TSoftObjectPtr<USkeletalMesh>
			constexpr auto MaleTorsoMeshHandsOnly = 0x15e0; // Size: 40, Type: struct TSoftObjectPtr<USkeletalMesh>
			constexpr auto FemaleTorsoMeshFullArms = 0x1608; // Size: 40, Type: struct TSoftObjectPtr<USkeletalMesh>
			constexpr auto FemaleTorsoMeshHalfArms = 0x1630; // Size: 40, Type: struct TSoftObjectPtr<USkeletalMesh>
			constexpr auto FemaleTorsoMeshHandsOnly = 0x1658; // Size: 40, Type: struct TSoftObjectPtr<USkeletalMesh>
			constexpr auto CameraShakeMoveForward = 0x1680; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto CameraShakeMoveForwardAiming = 0x16a8; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto CameraShakeMoveRight = 0x16d0; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto CameraShakeMoveRightAiming = 0x16f8; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto CameraShakeSprint = 0x1720; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto CameraShakeConsternation = 0x1748; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto NutClass = 0x1770; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto NutThrowForce = 0x1798; // Size: 4, Type: float
			constexpr auto AdditionalNutTransform = 0x17a0; // Size: 48, Type: struct FTransform
			constexpr auto AdditionalNutRotation = 0x17d0; // Size: 12, Type: struct FVector
			constexpr auto bIsDead = 0x17dc; // Size: 1, Type: bool
			constexpr auto NormalFOV = 0x17e0; // Size: 4, Type: float
			constexpr auto SprintFOV = 0x17e4; // Size: 4, Type: float
			constexpr auto NormalFOVChangeSpeed = 0x17e8; // Size: 4, Type: float
			constexpr auto OpticsFOVChangeSpeed = 0x17ec; // Size: 4, Type: float
			constexpr auto CameraBoneName = 0x17f0; // Size: 8, Type: struct FName
			constexpr auto DissolveLifespanTrigger = 0x17fc; // Size: 4, Type: float
			constexpr auto bIsClimbingLadder = 0x1810; // Size: 1, Type: bool
			constexpr auto m_ChickenStatus = 0x18c8; // Size: 1, Type: char
			constexpr auto BaseTurnRate = 0x18d8; // Size: 4, Type: float
			constexpr auto BaseLookUpRate = 0x18dc; // Size: 4, Type: float
			constexpr auto MouseSensivityMultiplier = 0x18e0; // Size: 4, Type: float
			constexpr auto WeaponDataTable = 0x18e8; // Size: 8, Type: struct UDataTable*
			constexpr auto IKFloorTraceOffset = 0x18f0; // Size: 12, Type: struct FVector
			constexpr auto IKFloorTraceLenth = 0x18fc; // Size: 4, Type: float
			constexpr auto bIKIsEnabled = 0x1900; // Size: 1, Type: bool
			constexpr auto bIKIsDebug = 0x1901; // Size: 1, Type: bool
			constexpr auto IKTraceDistance = 0x1904; // Size: 4, Type: float
			constexpr auto IKRightFootSocketName = 0x1908; // Size: 8, Type: struct FName
			constexpr auto IKLeftFootSocketName = 0x1910; // Size: 8, Type: struct FName
			constexpr auto IKScale = 0x1918; // Size: 4, Type: float
			constexpr auto PronedEyeHeight = 0x191c; // Size: 4, Type: float
			constexpr auto bIsProned = 0x1920; // Size: 1, Type: char
			constexpr auto bIsQuickItemChange = 0x1924; // Size: 1, Type: bool
			constexpr auto DissolveInterpSpeed = 0x192c; // Size: 4, Type: float
			constexpr auto m_bLockCameraRotation = 0x193d; // Size: 1, Type: bool
			constexpr auto CurrentLadder = 0x1998; // Size: 8, Type: struct AWTLLadder*
			constexpr auto RemoteViewYaw = 0x19a0; // Size: 1, Type: char
			constexpr auto StandaloneCharacterID = 0x19a8; // Size: 8, Type: uint64_t
			constexpr auto bIsMonstersFollowing = 0x19b8; // Size: 1, Type: bool
			constexpr auto MaxNumMonstersFollowing = 0x19bc; // Size: 4, Type: int32_t
			constexpr auto RadiusMonsterNear = 0x19c0; // Size: 4, Type: float
	}
} 
