namespace offsets
{
	namespace UAB_Male_TPC_Anim_C
	{
			constexpr auto UberGraphFrame = 0xfa0; // Size: 8, Type: struct FPointerToUberGraphFrame
			constexpr auto AnimGraphNode_SequencePlayer_36 = 0xfa8; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_Slot_14 = 0x1028; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace_10 = 0x1070; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_BlendListByBool_19 = 0x1200; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_SequencePlayer_35 = 0x12a0; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_ApplyAdditive_7 = 0x1320; // Size: 200, Type: struct FAnimNode_ApplyAdditive
			constexpr auto AnimGraphNode_UseCachedPose_57 = 0x13e8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_ApplyMeshSpaceAdditive_8 = 0x1410; // Size: 208, Type: struct FAnimNode_ApplyMeshSpaceAdditive
			constexpr auto AnimGraphNode_SequencePlayer_34 = 0x14e0; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_UseCachedPose_56 = 0x1560; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_55 = 0x1588; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_ApplyAdditive_6 = 0x15b0; // Size: 200, Type: struct FAnimNode_ApplyAdditive
			constexpr auto AnimGraphNode_UseCachedPose_54 = 0x1678; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_53 = 0x16a0; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_52 = 0x16c8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_51 = 0x16f0; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SequencePlayer_33 = 0x1718; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_BlendListByBool_18 = 0x1798; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_BlendSpacePlayer_19 = 0x1838; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendSpacePlayer_18 = 0x1920; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendSpacePlayer_17 = 0x1a08; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendSpacePlayer_16 = 0x1af0; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_LayeredBoneBlend_23 = 0x1bd8; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_SequencePlayer_32 = 0x1c98; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_BlendSpacePlayer_15 = 0x1d18; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_Slot_13 = 0x1e00; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_BlendSpacePlayer_14 = 0x1e48; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_LayeredBoneBlend_22 = 0x1f30; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_SequencePlayer_31 = 0x1ff0; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_Slot_12 = 0x2070; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_BlendSpacePlayer_13 = 0x20b8; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendSpacePlayer_12 = 0x21a0; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_SaveCachedPose_23 = 0x2288; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_SaveCachedPose_22 = 0x23e0; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_BlendListByEnum_4 = 0x2538; // Size: 176, Type: struct FAnimNode_BlendListByEnum
			constexpr auto AnimGraphNode_UseCachedPose_50 = 0x25e8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_BlendListByBool_17 = 0x2610; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_BlendSpacePlayer_11 = 0x26b0; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendListByEnum_3 = 0x2798; // Size: 176, Type: struct FAnimNode_BlendListByEnum
			constexpr auto AnimGraphNode_BlendListByEnum_2 = 0x2848; // Size: 176, Type: struct FAnimNode_BlendListByEnum
			constexpr auto AnimGraphNode_BlendListByEnum = 0x28f8; // Size: 176, Type: struct FAnimNode_BlendListByEnum
			constexpr auto AnimGraphNode_SaveCachedPose_21 = 0x29a8; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_49 = 0x2b00; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_Slot_11 = 0x2b28; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_Slot_10 = 0x2b70; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_BlendListByBool_16 = 0x2bb8; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_BlendSpacePlayer_10 = 0x2c58; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_TwoWayBlend_8 = 0x2d40; // Size: 200, Type: struct FAnimNode_TwoWayBlend
			constexpr auto AnimGraphNode_ModifyBone_80 = 0x2e08; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_79 = 0x2f10; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ComponentToLocalSpace_15 = 0x3018; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_LocalToComponentSpace_15 = 0x3038; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ModifyBone_78 = 0x3058; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_SequencePlayer_30 = 0x3160; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_BlendListByBool_15 = 0x31e0; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_ModifyBone_77 = 0x3280; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_76 = 0x3388; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_SaveCachedPose_20 = 0x3490; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_48 = 0x35e8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_47 = 0x3610; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_BlendSpacePlayer_9 = 0x3638; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendListByBool_14 = 0x3720; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_CopyBone_3 = 0x37c0; // Size: 240, Type: struct FAnimNode_CopyBone
			constexpr auto AnimGraphNode_LocalToComponentSpace_14 = 0x38b0; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ComponentToLocalSpace_14 = 0x38d0; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_LocalToComponentSpace_13 = 0x38f0; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_SequencePlayer_29 = 0x3910; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_BlendSpacePlayer_8 = 0x3990; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_LayeredBoneBlend_21 = 0x3a78; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_ModifyBone_75 = 0x3b38; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_74 = 0x3c40; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_73 = 0x3d48; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_72 = 0x3e50; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_71 = 0x3f58; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_70 = 0x4060; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_69 = 0x4168; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace_9 = 0x4270; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_LayeredBoneBlend_20 = 0x4400; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_SequencePlayer_28 = 0x44c0; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_BlendSpacePlayer_7 = 0x4540; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_ApplyMeshSpaceAdditive_7 = 0x4628; // Size: 208, Type: struct FAnimNode_ApplyMeshSpaceAdditive
			constexpr auto AnimGraphNode_BlendListByBool_13 = 0x46f8; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_UseCachedPose_46 = 0x4798; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_ApplyAdditive_5 = 0x47c0; // Size: 200, Type: struct FAnimNode_ApplyAdditive
			constexpr auto AnimGraphNode_Slot_9 = 0x4888; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_Slot_8 = 0x48d0; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_LayeredBoneBlend_19 = 0x4918; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_UseCachedPose_45 = 0x49d8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace_8 = 0x4a00; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_RotationMultiplier_4 = 0x4b90; // Size: 240, Type: struct FAnimNode_RotationMultiplier
			constexpr auto AnimGraphNode_RotationMultiplier_3 = 0x4c80; // Size: 240, Type: struct FAnimNode_RotationMultiplier
			constexpr auto AnimGraphNode_RotationMultiplier_2 = 0x4d70; // Size: 240, Type: struct FAnimNode_RotationMultiplier
			constexpr auto AnimGraphNode_RotationMultiplier = 0x4e60; // Size: 240, Type: struct FAnimNode_RotationMultiplier
			constexpr auto AnimGraphNode_ModifyBone_68 = 0x4f50; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_LayeredBoneBlend_18 = 0x5058; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_LayeredBoneBlend_17 = 0x5118; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_Fabrik_2 = 0x51e0; // Size: 400, Type: struct FAnimNode_Fabrik
			constexpr auto AnimGraphNode_SequencePlayer_27 = 0x5370; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_TwoWayBlend_7 = 0x53f0; // Size: 200, Type: struct FAnimNode_TwoWayBlend
			constexpr auto AnimGraphNode_UseCachedPose_44 = 0x54b8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SaveCachedPose_19 = 0x54e0; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_43 = 0x5638; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_TwoWayBlend_6 = 0x5660; // Size: 200, Type: struct FAnimNode_TwoWayBlend
			constexpr auto AnimGraphNode_UseCachedPose_42 = 0x5728; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SequencePlayer_26 = 0x5750; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_LayeredBoneBlend_16 = 0x57d0; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace_7 = 0x5890; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace_6 = 0x5a20; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_ApplyMeshSpaceAdditive_6 = 0x5bb0; // Size: 208, Type: struct FAnimNode_ApplyMeshSpaceAdditive
			constexpr auto AnimGraphNode_UseCachedPose_41 = 0x5c80; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SequencePlayer_25 = 0x5ca8; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_ApplyMeshSpaceAdditive_5 = 0x5d28; // Size: 208, Type: struct FAnimNode_ApplyMeshSpaceAdditive
			constexpr auto AnimGraphNode_UseCachedPose_40 = 0x5df8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SequencePlayer_24 = 0x5e20; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_UseCachedPose_39 = 0x5ea0; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace_5 = 0x5ec8; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_Slot_7 = 0x6058; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace_4 = 0x60a0; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_LayeredBoneBlend_15 = 0x6230; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_SaveCachedPose_18 = 0x62f0; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_38 = 0x6448; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_37 = 0x6470; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_LayeredBoneBlend_14 = 0x6498; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_Slot_6 = 0x6558; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_SaveCachedPose_17 = 0x65a0; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_36 = 0x66f8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_35 = 0x6720; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_ModifyBone_67 = 0x6748; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_Fabrik = 0x6850; // Size: 400, Type: struct FAnimNode_Fabrik
			constexpr auto AnimGraphNode_ModifyBone_66 = 0x69e0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_SequencePlayer_23 = 0x6ae8; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_ApplyAdditive_4 = 0x6b68; // Size: 200, Type: struct FAnimNode_ApplyAdditive
			constexpr auto AnimGraphNode_ModifyBone_65 = 0x6c30; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_64 = 0x6d38; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_63 = 0x6e40; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_62 = 0x6f48; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_61 = 0x7050; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_Slot_5 = 0x7158; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_LayeredBoneBlend_13 = 0x71a0; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_SaveCachedPose_16 = 0x7260; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_34 = 0x73b8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_33 = 0x73e0; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_ModifyBone_60 = 0x7408; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_59 = 0x7510; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_58 = 0x7618; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_57 = 0x7720; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_LocalToComponentSpace_12 = 0x7828; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ComponentToLocalSpace_13 = 0x7848; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_ModifyBone_56 = 0x7868; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_LocalToComponentSpace_11 = 0x7970; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ComponentToLocalSpace_12 = 0x7990; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_LayeredBoneBlend_12 = 0x79b0; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_ModifyBone_55 = 0x7a70; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_54 = 0x7b78; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_UseCachedPose_32 = 0x7c80; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_ModifyBone_53 = 0x7ca8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_SaveCachedPose_15 = 0x7db0; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_31 = 0x7f08; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_30 = 0x7f30; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_LayeredBoneBlend_11 = 0x7f58; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_ComponentToLocalSpace_11 = 0x8018; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_LocalToComponentSpace_10 = 0x8038; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_TwoBoneIK_12 = 0x8060; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_LayeredBoneBlend_10 = 0x8240; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_ComponentToLocalSpace_10 = 0x8300; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_TwoBoneIK_11 = 0x8320; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_TwoBoneIK_10 = 0x8500; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_ModifyBone_52 = 0x86e0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_51 = 0x87e8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_50 = 0x88f0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_49 = 0x89f8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_48 = 0x8b00; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_47 = 0x8c08; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_46 = 0x8d10; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_45 = 0x8e18; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_44 = 0x8f20; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_43 = 0x9028; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_42 = 0x9130; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_41 = 0x9238; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_40 = 0x9340; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_39 = 0x9448; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_38 = 0x9550; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_37 = 0x9658; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_36 = 0x9760; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_35 = 0x9868; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_LayeredBoneBlend_9 = 0x9970; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_SequencePlayer_22 = 0x9a30; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_ModifyBone_34 = 0x9ab0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_33 = 0x9bb8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_CopyBone_2 = 0x9cc0; // Size: 240, Type: struct FAnimNode_CopyBone
			constexpr auto AnimGraphNode_ModifyBone_32 = 0x9db0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_LocalToComponentSpace_9 = 0x9eb8; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ModifyBone_31 = 0x9ed8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ComponentToLocalSpace_9 = 0x9fe0; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_ModifyBone_30 = 0xa000; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_29 = 0xa108; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_28 = 0xa210; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_27 = 0xa318; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_26 = 0xa420; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_SaveCachedPose_14 = 0xa528; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_29 = 0xa680; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SaveCachedPose_13 = 0xa6a8; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_TwoWayBlend_5 = 0xa800; // Size: 200, Type: struct FAnimNode_TwoWayBlend
			constexpr auto AnimGraphNode_UseCachedPose_28 = 0xa8c8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_27 = 0xa8f0; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_26 = 0xa918; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SequencePlayer_21 = 0xa940; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_UseCachedPose_25 = 0xa9c0; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_ModifyBone_25 = 0xa9e8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_24 = 0xaaf0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_UseCachedPose_24 = 0xabf8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_LocalToComponentSpace_8 = 0xac20; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ComponentToLocalSpace_8 = 0xac40; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_SaveCachedPose_12 = 0xac60; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_SaveCachedPose_11 = 0xadb8; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_SaveCachedPose_10 = 0xaf10; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_SequencePlayer_20 = 0xb068; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_LocalToComponentSpace_7 = 0xb0e8; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_TwoBoneIK_9 = 0xb110; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_TwoBoneIK_8 = 0xb2f0; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_ModifyBone_23 = 0xb4d0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ComponentToLocalSpace_7 = 0xb5d8; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_SaveCachedPose_9 = 0xb5f8; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_23 = 0xb750; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_22 = 0xb778; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_LocalToComponentSpace_6 = 0xb7a0; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ComponentToLocalSpace_6 = 0xb7c0; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_LocalToComponentSpace_5 = 0xb7e0; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ComponentToLocalSpace_5 = 0xb800; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_SaveCachedPose_8 = 0xb820; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_TwoWayBlend_4 = 0xb978; // Size: 200, Type: struct FAnimNode_TwoWayBlend
			constexpr auto AnimGraphNode_BlendListByBool_12 = 0xba40; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_UseCachedPose_21 = 0xbae0; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SequencePlayer_19 = 0xbb08; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_BlendListByBool_11 = 0xbb88; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_ModifyBone_22 = 0xbc28; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_CopyBone = 0xbd30; // Size: 240, Type: struct FAnimNode_CopyBone
			constexpr auto AnimGraphNode_ModifyBone_21 = 0xbe20; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_20 = 0xbf28; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace_3 = 0xc030; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_LayeredBoneBlend_8 = 0xc1c0; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_UseCachedPose_20 = 0xc280; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_ModifyBone_19 = 0xc2a8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_18 = 0xc3b0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_BlendListByBool_10 = 0xc4b8; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_SequencePlayer_18 = 0xc558; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_SequencePlayer_17 = 0xc5d8; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_BlendListByBool_9 = 0xc658; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_SaveCachedPose_7 = 0xc6f8; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace_2 = 0xc850; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_BlendListByBool_8 = 0xc9e0; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_SequencePlayer_16 = 0xca80; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_BlendSpacePlayer_6 = 0xcb00; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendListByBool_7 = 0xcbe8; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_BlendListByBool_6 = 0xcc88; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_SequencePlayer_15 = 0xcd28; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_SequencePlayer_14 = 0xcda8; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_BlendListByBool_5 = 0xce28; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_Slot_4 = 0xcec8; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_ApplyAdditive_3 = 0xcf10; // Size: 200, Type: struct FAnimNode_ApplyAdditive
			constexpr auto AnimGraphNode_SequencePlayer_13 = 0xcfd8; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_RotationOffsetBlendSpace = 0xd058; // Size: 400, Type: struct FAnimNode_RotationOffsetBlendSpace
			constexpr auto AnimGraphNode_BlendSpacePlayer_5 = 0xd1e8; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_SequencePlayer_12 = 0xd2d0; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_ApplyAdditive_2 = 0xd350; // Size: 200, Type: struct FAnimNode_ApplyAdditive
			constexpr auto AnimGraphNode_SequencePlayer_11 = 0xd418; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_ModifyBone_17 = 0xd498; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_TwoBoneIK_7 = 0xd5a0; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_LocalToComponentSpace_4 = 0xd780; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ComponentToLocalSpace_4 = 0xd7a0; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_TwoBoneIK_6 = 0xd7c0; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_ModifyBone_16 = 0xd9a0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_SaveCachedPose_6 = 0xdaa8; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_SaveCachedPose_5 = 0xdc00; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_19 = 0xdd58; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_18 = 0xdd80; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_17 = 0xdda8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_TwoBoneIK_5 = 0xddd0; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_ApplyAdditive = 0xdfb0; // Size: 200, Type: struct FAnimNode_ApplyAdditive
			constexpr auto AnimGraphNode_ModifyBone_15 = 0xe078; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_UseCachedPose_16 = 0xe180; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_TwoBoneIK_4 = 0xe1b0; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_ModifyBone_14 = 0xe390; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_LayeredBoneBlend_7 = 0xe498; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_UseCachedPose_15 = 0xe558; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_14 = 0xe580; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_ModifyBone_13 = 0xe5a8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_LayeredBoneBlend_6 = 0xe6b0; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_LocalToComponentSpace_3 = 0xe770; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_SaveCachedPose_4 = 0xe790; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_TransitionResult_21 = 0xe8e8; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_20 = 0xe910; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_19 = 0xe938; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_18 = 0xe960; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_17 = 0xe988; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_16 = 0xe9b0; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_15 = 0xe9d8; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_14 = 0xea00; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_13 = 0xea28; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_12 = 0xea50; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_11 = 0xea78; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_10 = 0xeaa0; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_9 = 0xeac8; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_8 = 0xeaf0; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_7 = 0xeb18; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_6 = 0xeb40; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_SequencePlayer_10 = 0xeb68; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_StateResult_12 = 0xebe8; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_ApplyMeshSpaceAdditive_4 = 0xec18; // Size: 208, Type: struct FAnimNode_ApplyMeshSpaceAdditive
			constexpr auto AnimGraphNode_SequencePlayer_9 = 0xece8; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_UseCachedPose_13 = 0xed68; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_StateResult_11 = 0xed90; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_SequencePlayer_8 = 0xedc0; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_StateResult_10 = 0xee40; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_SequencePlayer_7 = 0xee70; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_StateResult_9 = 0xeef0; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_ApplyMeshSpaceAdditive_3 = 0xef20; // Size: 208, Type: struct FAnimNode_ApplyMeshSpaceAdditive
			constexpr auto AnimGraphNode_SequencePlayer_6 = 0xeff0; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_UseCachedPose_12 = 0xf070; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_StateResult_8 = 0xf098; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_SequencePlayer_5 = 0xf0c8; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_StateResult_7 = 0xf148; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_SequencePlayer_4 = 0xf178; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_StateResult_6 = 0xf1f8; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_UseCachedPose_11 = 0xf228; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_StateResult_5 = 0xf250; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_StateMachine_2 = 0xf280; // Size: 176, Type: struct FAnimNode_StateMachine
			constexpr auto AnimGraphNode_TwoWayBlend_3 = 0xf330; // Size: 200, Type: struct FAnimNode_TwoWayBlend
			constexpr auto AnimGraphNode_TwoBoneIK_3 = 0xf400; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_LayeredBoneBlend_5 = 0xf5e0; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_UseCachedPose_10 = 0xf6a0; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_9 = 0xf6c8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_TwoBoneIK_2 = 0xf6f0; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_BlendListByBool_4 = 0xf8d0; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_UseCachedPose_8 = 0xf970; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_LayeredBoneBlend_4 = 0xf998; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_LayeredBoneBlend_3 = 0xfa58; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_ComponentToLocalSpace_3 = 0xfb18; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_ModifyBone_12 = 0xfb38; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_BlendListByBool_3 = 0xfc40; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_ModifyBone_11 = 0xfce0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_UseCachedPose_7 = 0xfde8; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SaveCachedPose_3 = 0xfe10; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_UseCachedPose_6 = 0xff68; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_LayeredBoneBlend_2 = 0xff90; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_ModifyBone_10 = 0x10050; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_9 = 0x10158; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_8 = 0x10260; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_BlendSpacePlayer_4 = 0x10368; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_TwoBoneIK = 0x10450; // Size: 480, Type: struct FAnimNode_TwoBoneIK
			constexpr auto AnimGraphNode_ModifyBone_7 = 0x10630; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_LocalToComponentSpace_2 = 0x10738; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_ComponentToLocalSpace_2 = 0x10758; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_ModifyBone_6 = 0x10778; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_5 = 0x10880; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ComponentToLocalSpace = 0x10988; // Size: 32, Type: struct FAnimNode_ConvertComponentToLocalSpace
			constexpr auto AnimGraphNode_ApplyMeshSpaceAdditive_2 = 0x109a8; // Size: 208, Type: struct FAnimNode_ApplyMeshSpaceAdditive
			constexpr auto AnimGraphNode_BlendSpacePlayer_3 = 0x10a78; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendSpacePlayer_2 = 0x10b60; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendListByBool_2 = 0x10c48; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_ModifyBone_4 = 0x10ce8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_3 = 0x10df0; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone_2 = 0x10ef8; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_ModifyBone = 0x11000; // Size: 264, Type: struct FAnimNode_ModifyBone
			constexpr auto AnimGraphNode_UseCachedPose_5 = 0x11108; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_Slot_3 = 0x11130; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_LocalToComponentSpace = 0x11178; // Size: 32, Type: struct FAnimNode_ConvertLocalToComponentSpace
			constexpr auto AnimGraphNode_BlendSpacePlayer = 0x11198; // Size: 232, Type: struct FAnimNode_BlendSpacePlayer
			constexpr auto AnimGraphNode_BlendListByBool = 0x11280; // Size: 160, Type: struct FAnimNode_BlendListByBool
			constexpr auto AnimGraphNode_LayeredBoneBlend = 0x11320; // Size: 192, Type: struct FAnimNode_LayeredBoneBlend
			constexpr auto AnimGraphNode_Slot_2 = 0x113e0; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_SaveCachedPose_2 = 0x11428; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_SaveCachedPose = 0x11580; // Size: 344, Type: struct FAnimNode_SaveCachedPose
			constexpr auto AnimGraphNode_TransitionResult_5 = 0x116d8; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_4 = 0x11700; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_3 = 0x11728; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult_2 = 0x11750; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_TransitionResult = 0x11778; // Size: 40, Type: struct FAnimNode_TransitionResult
			constexpr auto AnimGraphNode_ApplyMeshSpaceAdditive = 0x117a0; // Size: 208, Type: struct FAnimNode_ApplyMeshSpaceAdditive
			constexpr auto AnimGraphNode_UseCachedPose_4 = 0x11870; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SequencePlayer_3 = 0x11898; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_StateResult_4 = 0x11918; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_TwoWayBlend_2 = 0x11948; // Size: 200, Type: struct FAnimNode_TwoWayBlend
			constexpr auto AnimGraphNode_UseCachedPose_3 = 0x11a10; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_SequencePlayer_2 = 0x11a38; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_StateResult_3 = 0x11ab8; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_SequencePlayer = 0x11ae8; // Size: 128, Type: struct FAnimNode_SequencePlayer
			constexpr auto AnimGraphNode_StateResult_2 = 0x11b68; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_UseCachedPose_2 = 0x11b98; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_StateResult = 0x11bc0; // Size: 48, Type: struct FAnimNode_StateResult
			constexpr auto AnimGraphNode_StateMachine = 0x11bf0; // Size: 176, Type: struct FAnimNode_StateMachine
			constexpr auto AnimGraphNode_Slot = 0x11ca0; // Size: 72, Type: struct FAnimNode_Slot
			constexpr auto AnimGraphNode_TwoWayBlend = 0x11ce8; // Size: 200, Type: struct FAnimNode_TwoWayBlend
			constexpr auto AnimGraphNode_UseCachedPose = 0x11db0; // Size: 40, Type: struct FAnimNode_UseCachedPose
			constexpr auto AnimGraphNode_Root = 0x11dd8; // Size: 48, Type: struct FAnimNode_Root
			constexpr auto RotationSpeedHorizontalWithDirectionMultiplier = 0x11e08; // Size: 4, Type: float
			constexpr auto RootBoneRotation = 0x11e0c; // Size: 12, Type: struct FRotator
			constexpr auto RotationSpeedHorizontalWithDirectionCurrent = 0x11e18; // Size: 4, Type: float
			constexpr auto FootOffset_R = 0x11e1c; // Size: 4, Type: float
			constexpr auto FootOffset_L = 0x11e20; // Size: 4, Type: float
			constexpr auto PelvisZOffset = 0x11e24; // Size: 4, Type: float
			constexpr auto FootRotation_R = 0x11e28; // Size: 12, Type: struct FRotator
			constexpr auto FootRotation_L = 0x11e34; // Size: 12, Type: struct FRotator
			constexpr auto FootRotation_R_Alpha = 0x11e40; // Size: 4, Type: float
			constexpr auto FootRotation_L_Alpha = 0x11e44; // Size: 4, Type: float
			constexpr auto PelvisZOffsetTarget = 0x11e48; // Size: 4, Type: float
			constexpr auto FootOffset_R_Target = 0x11e4c; // Size: 4, Type: float
			constexpr auto FootOffset_L_Target = 0x11e50; // Size: 4, Type: float
			constexpr auto IsPKM = 0x11e54; // Size: 1, Type: bool
			constexpr auto PKM_RotationPoint = 0x11e58; // Size: 12, Type: struct FVector
			constexpr auto PKM_Offset = 0x11e64; // Size: 12, Type: struct FVector
			constexpr auto PKM_CameraAimOffsetVector = 0x11e70; // Size: 12, Type: struct FVector
			constexpr auto PKM_CameraAimOffsetVectorInverse = 0x11e7c; // Size: 12, Type: struct FVector
			constexpr auto IK_LeftHand_Alpha = 0x11e88; // Size: 4, Type: float
			constexpr auto IK_RightHand_Alpha = 0x11e8c; // Size: 4, Type: float
			constexpr auto EmptyHandsCurveValue = 0x11e90; // Size: 4, Type: float
			constexpr auto AimOffsetHeadRotation = 0x11e94; // Size: 12, Type: struct FRotator
			constexpr auto PickupAlpha = 0x11ea0; // Size: 4, Type: float
			constexpr auto PickupFABRICEffectorTransform = 0x11eb0; // Size: 48, Type: struct FTransform
			constexpr auto MixEmptyHands = 0x11ee0; // Size: 4, Type: float
			constexpr auto MinCameraOffset = 0x11ee4; // Size: 4, Type: float
			constexpr auto WeaponAimOffset = 0x11ee8; // Size: 4, Type: float
			constexpr auto Rest = 0x11eec; // Size: 4, Type: float
			constexpr auto OneMinusRest = 0x11ef0; // Size: 4, Type: float
			constexpr auto ActionSlotAlpha = 0x11ef4; // Size: 4, Type: float
			constexpr auto BackpackTranslation = 0x11ef8; // Size: 12, Type: struct FVector
			constexpr auto IK_Foot_Alpha = 0x11f04; // Size: 4, Type: float
			constexpr auto PDA_Alpha = 0x11f08; // Size: 4, Type: float
			constexpr auto HandsAimOffsetUpAlpha = 0x11f0c; // Size: 4, Type: float
			constexpr auto HandsAimOffsetUpTranslationOffset = 0x11f10; // Size: 12, Type: struct FVector
			constexpr auto IsRunAlpha = 0x11f1c; // Size: 4, Type: float
			constexpr auto SexAlpha = 0x11f20; // Size: 4, Type: float
			constexpr auto FemaleGrenadeDownOffset = 0x11f24; // Size: 12, Type: struct FVector
			constexpr auto FemaleGrenadeMiddleDwnffset = 0x11f30; // Size: 12, Type: struct FVector
			constexpr auto MyDeltaTime = 0x11f3c; // Size: 4, Type: float
			constexpr auto IKHand_L = 0x11f40; // Size: 4, Type: float
			constexpr auto IsServer = 0x11f44; // Size: 1, Type: bool
			constexpr auto Spike = 0x11f48; // Size: 8, Type: struct ABP_Devourer_Projectile_C*
			constexpr auto MinSpeedToSwitchSwimmigStates = 0x11f50; // Size: 4, Type: float
			constexpr auto SwimmingAlpha = 0x11f54; // Size: 4, Type: float
			constexpr auto InVehicle = 0x11f58; // Size: 1, Type: bool
			constexpr auto WheelAngle_1 = 0x11f5c; // Size: 4, Type: float
			constexpr auto Vector_FootOffset_R = 0x11f60; // Size: 12, Type: struct FVector
			constexpr auto Vector_FootOffset_L_1 = 0x11f6c; // Size: 12, Type: struct FVector
			constexpr auto Vector_PelvisZOffset = 0x11f78; // Size: 12, Type: struct FVector
			constexpr auto Rotator_BodyUnderWater = 0x11f84; // Size: 12, Type: struct FRotator
			constexpr auto Alpha_RHCenter = 0x11f90; // Size: 4, Type: float
			constexpr auto Alpha_RHDown = 0x11f94; // Size: 4, Type: float
			constexpr auto Alpha_RHUp = 0x11f98; // Size: 4, Type: float
			constexpr auto Alpha_LHCenter = 0x11f9c; // Size: 4, Type: float
			constexpr auto Alpha_LHDown = 0x11fa0; // Size: 4, Type: float
			constexpr auto Alpha_LHUp = 0x11fa4; // Size: 4, Type: float
			constexpr auto alpha_upperarm_l = 0x11fa8; // Size: 4, Type: float
			constexpr auto alpha_lowerarm_l = 0x11fac; // Size: 4, Type: float
			constexpr auto alpha_lowerarm_l2 = 0x11fb0; // Size: 4, Type: float
			constexpr auto alpha_AimOffsetBoneRotation = 0x11fb4; // Size: 4, Type: float
			constexpr auto alpha_AimOffsetBoneRotation_Velosity = 0x11fb8; // Size: 4, Type: float
			constexpr auto KnifeOnRunAttack_L = 0x11fbc; // Size: 4, Type: float
			constexpr auto KnifeOnRunAttack_R = 0x11fc0; // Size: 4, Type: float
			constexpr auto KnifeOnRunAttack = 0x11fc4; // Size: 4, Type: float
			constexpr auto Inspect = 0x11fc8; // Size: 4, Type: float
			constexpr auto Debug_Crouch = 0x11fcc; // Size: 1, Type: bool
			constexpr auto RotInVehicle = 0x11fd0; // Size: 12, Type: struct FRotator
			constexpr auto bIsInVehicle = 0x11fdc; // Size: 1, Type: bool
			constexpr auto CurrentHandsOffsetWithMonocular = 0x11fe0; // Size: 12, Type: struct FVector
			constexpr auto MSRAlpha = 0x11fec; // Size: 4, Type: float
			constexpr auto MSRDesiredAlpha = 0x11ff0; // Size: 4, Type: float
			constexpr auto BadWeponIDList = 0x11ff8; // Size: 16, Type: struct TArray<int32_t>
			constexpr auto bUseMortar = 0x12008; // Size: 1, Type: bool
			constexpr auto MortarLeftHandTarget = 0x1200c; // Size: 12, Type: struct FVector
			constexpr auto MortarRightHandTarget = 0x12018; // Size: 12, Type: struct FVector
			constexpr auto MortarInclineAlphaInterp = 0x12024; // Size: 4, Type: float
			constexpr auto bFishing = 0x12028; // Size: 1, Type: bool
			constexpr auto TiltWithRod = 0x1202c; // Size: 4, Type: float
			constexpr auto Test_IKHand_L = 0x12030; // Size: 4, Type: float
			constexpr auto Test_IKHand_R = 0x12034; // Size: 4, Type: float
	}
} 
