namespace offsets
{
	namespace UPrimitiveComponent
	{
			constexpr auto MinDrawDistance = 0x200; // Size: 4, Type: float
			constexpr auto LDMaxDrawDistance = 0x204; // Size: 4, Type: float
			constexpr auto CachedMaxDrawDistance = 0x208; // Size: 4, Type: float
			constexpr auto DepthPriorityGroup = 0x20c; // Size: 1, Type: enum class ESceneDepthPriorityGroup
			constexpr auto ViewOwnerDepthPriorityGroup = 0x20d; // Size: 1, Type: enum class ESceneDepthPriorityGroup
			constexpr auto IndirectLightingCacheQuality = 0x20e; // Size: 1, Type: enum class EIndirectLightingCacheQuality
			constexpr auto LightmapType = 0x20f; // Size: 1, Type: enum class ELightmapType
			constexpr auto bUseMaxLODAsImposter = 0x210; // Size: 1, Type: char
			constexpr auto bBatchImpostersAsInstances = 0x210; // Size: 1, Type: char
			constexpr auto bNeverDistanceCull = 0x210; // Size: 1, Type: char
			constexpr auto bAlwaysCreatePhysicsState = 0x210; // Size: 1, Type: char
			constexpr auto bGenerateOverlapEvents = 0x211; // Size: 1, Type: char
			constexpr auto bMultiBodyOverlap = 0x211; // Size: 1, Type: char
			constexpr auto bTraceComplexOnMove = 0x211; // Size: 1, Type: char
			constexpr auto bReturnMaterialOnMove = 0x211; // Size: 1, Type: char
			constexpr auto bUseViewOwnerDepthPriorityGroup = 0x211; // Size: 1, Type: char
			constexpr auto bAllowCullDistanceVolume = 0x211; // Size: 1, Type: char
			constexpr auto bHasMotionBlurVelocityMeshes = 0x211; // Size: 1, Type: char
			constexpr auto bVisibleInReflectionCaptures = 0x211; // Size: 1, Type: char
			constexpr auto bVisibleInRealTimeSkyCaptures = 0x212; // Size: 1, Type: char
			constexpr auto bVisibleInRayTracing = 0x212; // Size: 1, Type: char
			constexpr auto bRenderInMainPass = 0x212; // Size: 1, Type: char
			constexpr auto bRenderInDepthPass = 0x212; // Size: 1, Type: char
			constexpr auto bReceivesDecals = 0x212; // Size: 1, Type: char
			constexpr auto bOwnerNoSee = 0x212; // Size: 1, Type: char
			constexpr auto bOnlyOwnerSee = 0x212; // Size: 1, Type: char
			constexpr auto bTreatAsBackgroundForOcclusion = 0x212; // Size: 1, Type: char
			constexpr auto bUseAsOccluder = 0x213; // Size: 1, Type: char
			constexpr auto bSelectable = 0x213; // Size: 1, Type: char
			constexpr auto bForceMipStreaming = 0x213; // Size: 1, Type: char
			constexpr auto bHasPerInstanceHitProxies = 0x213; // Size: 1, Type: char
			constexpr auto CastShadow = 0x213; // Size: 1, Type: char
			constexpr auto bAffectDynamicIndirectLighting = 0x213; // Size: 1, Type: char
			constexpr auto bAffectDistanceFieldLighting = 0x213; // Size: 1, Type: char
			constexpr auto bCastDynamicShadow = 0x213; // Size: 1, Type: char
			constexpr auto bCastStaticShadow = 0x214; // Size: 1, Type: char
			constexpr auto bCastVolumetricTranslucentShadow = 0x214; // Size: 1, Type: char
			constexpr auto bCastContactShadow = 0x214; // Size: 1, Type: char
			constexpr auto bSelfShadowOnly = 0x214; // Size: 1, Type: char
			constexpr auto bCastFarShadow = 0x214; // Size: 1, Type: char
			constexpr auto bCastInsetShadow = 0x214; // Size: 1, Type: char
			constexpr auto bCastCinematicShadow = 0x214; // Size: 1, Type: char
			constexpr auto bCastHiddenShadow = 0x214; // Size: 1, Type: char
			constexpr auto bCastShadowAsTwoSided = 0x215; // Size: 1, Type: char
			constexpr auto bLightAsIfStatic = 0x215; // Size: 1, Type: char
			constexpr auto bLightAttachmentsAsGroup = 0x215; // Size: 1, Type: char
			constexpr auto bExcludeFromLightAttachmentGroup = 0x215; // Size: 1, Type: char
			constexpr auto bReceiveMobileCSMShadows = 0x215; // Size: 1, Type: char
			constexpr auto bSingleSampleShadowFromStationaryLights = 0x215; // Size: 1, Type: char
			constexpr auto bIgnoreRadialImpulse = 0x215; // Size: 1, Type: char
			constexpr auto bIgnoreRadialForce = 0x215; // Size: 1, Type: char
			constexpr auto bApplyImpulseOnDamage = 0x216; // Size: 1, Type: char
			constexpr auto bReplicatePhysicsToAutonomousProxy = 0x216; // Size: 1, Type: char
			constexpr auto bFillCollisionUnderneathForNavmesh = 0x216; // Size: 1, Type: char
			constexpr auto AlwaysLoadOnClient = 0x216; // Size: 1, Type: char
			constexpr auto AlwaysLoadOnServer = 0x216; // Size: 1, Type: char
			constexpr auto bUseEditorCompositing = 0x216; // Size: 1, Type: char
			constexpr auto bRenderCustomDepth = 0x216; // Size: 1, Type: char
			constexpr auto bHasCustomNavigableGeometry = 0x217; // Size: 1, Type: enum class EHasCustomNavigableGeometry
			constexpr auto CanCharacterStepUpOn = 0x219; // Size: 1, Type: enum class ECanBeCharacterBase
			constexpr auto LightingChannels = 0x21a; // Size: 1, Type: struct FLightingChannels
			constexpr auto CustomDepthStencilWriteMask = 0x21b; // Size: 1, Type: enum class ERendererStencilMask
			constexpr auto CustomDepthStencilValue = 0x21c; // Size: 4, Type: int32_t
			constexpr auto CustomPrimitiveData = 0x220; // Size: 16, Type: struct FCustomPrimitiveData
			constexpr auto CustomPrimitiveDataInternal = 0x230; // Size: 16, Type: struct FCustomPrimitiveData
			constexpr auto TranslucencySortPriority = 0x248; // Size: 4, Type: int32_t
			constexpr auto VisibilityId = 0x24c; // Size: 4, Type: int32_t
			constexpr auto RuntimeVirtualTextures = 0x250; // Size: 16, Type: struct TArray<struct URuntimeVirtualTexture*>
			constexpr auto VirtualTextureLodBias = 0x260; // Size: 1, Type: int8_t
			constexpr auto VirtualTextureCullMips = 0x261; // Size: 1, Type: int8_t
			constexpr auto VirtualTextureMinCoverage = 0x262; // Size: 1, Type: int8_t
			constexpr auto VirtualTextureRenderPassType = 0x263; // Size: 1, Type: enum class ERuntimeVirtualTextureMainPassType
			constexpr auto LpvBiasMultiplier = 0x268; // Size: 4, Type: float
			constexpr auto BoundsScale = 0x274; // Size: 4, Type: float
			constexpr auto MoveIgnoreActors = 0x288; // Size: 16, Type: struct TArray<struct AActor*>
			constexpr auto MoveIgnoreComponents = 0x298; // Size: 16, Type: struct TArray<struct UPrimitiveComponent*>
			constexpr auto BodyInstance = 0x2b8; // Size: 344, Type: struct FBodyInstance
			constexpr auto OnComponentHit = 0x410; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentBeginOverlap = 0x411; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentEndOverlap = 0x412; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentWake = 0x413; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnComponentSleep = 0x414; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnBeginCursorOver = 0x416; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnEndCursorOver = 0x417; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnClicked = 0x418; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnReleased = 0x419; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchBegin = 0x41a; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchEnd = 0x41b; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchEnter = 0x41c; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto OnInputTouchLeave = 0x41d; // Size: 1, Type: struct FMulticastSparseDelegate
			constexpr auto LODParentPrimitive = 0x438; // Size: 8, Type: struct UPrimitiveComponent*
	}
} 
