namespace offsets
{
	namespace UWTLPDAMap
	{
			constexpr auto bMapScreen = 0x290; // Size: 8, Type: struct UBorder*
			constexpr auto slZoom = 0x298; // Size: 8, Type: struct USlider*
			constexpr auto ucBtnFindPlayerMarker = 0x2a0; // Size: 8, Type: struct UWTLCommonButton*
			constexpr auto cbFindPlayerMarker = 0x2a8; // Size: 8, Type: struct UWTLCommonCheckBox*
			constexpr auto ucBtnLegend = 0x2b0; // Size: 8, Type: struct UWTLCommonButton*
			constexpr auto ucBtnMarkers = 0x2b8; // Size: 8, Type: struct UWTLCommonButton*
			constexpr auto ucBtnLocationsList = 0x2c0; // Size: 8, Type: struct UWTLCommonButton*
			constexpr auto bSectorPosition = 0x2c8; // Size: 8, Type: struct UBorder*
			constexpr auto tbSectorPosition = 0x2d0; // Size: 8, Type: struct UTextBlock*
			constexpr auto cpNoSatelliteSignal = 0x2d8; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto cpMapLoadedFromModule = 0x2e0; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto bLegend = 0x2e8; // Size: 8, Type: struct UBorder*
			constexpr auto bLegendTitle = 0x2f0; // Size: 8, Type: struct UBorder*
			constexpr auto bLegendShowState = 0x2f8; // Size: 8, Type: struct UBorder*
			constexpr auto bMarkers = 0x300; // Size: 8, Type: struct UBorder*
			constexpr auto bMarkersTitle = 0x308; // Size: 8, Type: struct UBorder*
			constexpr auto bMarkersButtons = 0x310; // Size: 8, Type: struct UBorder*
			constexpr auto tbCurrentMarkersCount = 0x318; // Size: 8, Type: struct UTextBlock*
			constexpr auto tbMaxMarkersCount = 0x320; // Size: 8, Type: struct UTextBlock*
			constexpr auto sbLegendItems = 0x328; // Size: 8, Type: struct UScrollBox*
			constexpr auto sbMarkerItems = 0x330; // Size: 8, Type: struct UScrollBox*
			constexpr auto sbLocationItems = 0x338; // Size: 8, Type: struct UScrollBox*
			constexpr auto tbEmptyMarkersListTitle = 0x340; // Size: 8, Type: struct UTextBlock*
			constexpr auto cbShowAllLegendItems = 0x348; // Size: 8, Type: struct UWTLCommonCheckBox*
			constexpr auto ucBtnAddMarker = 0x350; // Size: 8, Type: struct UWTLCommonButton*
			constexpr auto ucBtnRemoveAllMarkers = 0x358; // Size: 8, Type: struct UWTLCommonButton*
			constexpr auto bLocationsList = 0x360; // Size: 8, Type: struct UBorder*
			constexpr auto bLocationsListTitle = 0x368; // Size: 8, Type: struct UBorder*
			constexpr auto bLocationsListItems = 0x370; // Size: 8, Type: struct UBorder*
			constexpr auto bSetMarkerHint = 0x378; // Size: 8, Type: struct UBorder*
			constexpr auto tbSetMarkerHint = 0x380; // Size: 8, Type: struct UTextBlock*
			constexpr auto maMap = 0x388; // Size: 8, Type: struct UMenuAnchor*
			constexpr auto bMarkerParametersBackground = 0x390; // Size: 8, Type: struct UBorder*
			constexpr auto vbMarkerParameters = 0x398; // Size: 8, Type: struct UVerticalBox*
			constexpr auto bMarkerParametersTitle = 0x3a0; // Size: 8, Type: struct UBorder*
			constexpr auto bMarkerParametersButtons = 0x3a8; // Size: 8, Type: struct UBorder*
			constexpr auto ucMarkerColorPicker = 0x3b0; // Size: 8, Type: struct UWTLUtilityColorPicker*
			constexpr auto etbMarkerName = 0x3b8; // Size: 8, Type: struct UEditableTextBox*
			constexpr auto cbMarkerSticking = 0x3c0; // Size: 8, Type: struct UWTLCommonCheckBox*
			constexpr auto wpMarkersSubTypes = 0x3c8; // Size: 8, Type: struct UWrapBox*
			constexpr auto ucBtnSetMarker = 0x3d0; // Size: 8, Type: struct UWTLCommonButton*
			constexpr auto ucBtnSetMarkerCancel = 0x3d8; // Size: 8, Type: struct UWTLCommonButton*
			constexpr auto cpMarker = 0x3e0; // Size: 8, Type: struct UCanvasPanel*
			constexpr auto szbMap = 0x3e8; // Size: 8, Type: struct USizeBox*
			constexpr auto imgMap = 0x3f0; // Size: 8, Type: struct UImage*
			constexpr auto tbMarkerParametersTitle = 0x3f8; // Size: 8, Type: struct UTextBlock*
			constexpr auto tbMarkersTitle = 0x400; // Size: 8, Type: struct UTextBlock*
			constexpr auto tbLegendItemsShowState = 0x408; // Size: 8, Type: struct UTextBlock*
			constexpr auto m_MapPopupMenuWidget = 0x580; // Size: 8, Type: struct UWTLCommonPopupMenu*
			constexpr auto DefaultMapItemData = 0x590; // Size: 280, Type: struct FWTLMapItemData
			constexpr auto LegendItemsMinSizeX = 0x6a8; // Size: 4, Type: float
			constexpr auto LegendItemsMaxSizeX = 0x6ac; // Size: 4, Type: float
			constexpr auto LegendItemsOriginalMaxSizeY = 0x6b0; // Size: 4, Type: float
			constexpr auto LegendItemsMaxVisibleItems = 0x6b4; // Size: 4, Type: int32_t
			constexpr auto LegendItemsElementHeight = 0x6b8; // Size: 4, Type: float
			constexpr auto MarkerItemsOriginalSizeX = 0x6bc; // Size: 4, Type: float
			constexpr auto MarkerItemsOriginalMaxSizeY = 0x6c0; // Size: 4, Type: float
			constexpr auto MarkerItemsMaxVisibleItems = 0x6c4; // Size: 4, Type: int32_t
			constexpr auto MarkerItemsElementHeight = 0x6c8; // Size: 4, Type: float
			constexpr auto LocationItemsMinSizeX = 0x6cc; // Size: 4, Type: float
			constexpr auto LocationItemsOriginalMaxSizeY = 0x6d0; // Size: 4, Type: float
			constexpr auto LocationItemsMaxVisibleItems = 0x6d4; // Size: 4, Type: int32_t
			constexpr auto LocationItemsElementHeight = 0x6d8; // Size: 4, Type: float
			constexpr auto PDALegendItemClass = 0x6e0; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto PDAMarkerListItemClass = 0x708; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto PDALocationsListItemClass = 0x730; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto MapMarkerClass = 0x758; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto PopupMenuWidgetClass = 0x780; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto MarkerSubTypeItemClass = 0x7a8; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto SetMarkerHintBlinkingAnimation = 0x7d0; // Size: 8, Type: struct UWidgetAnimation*
			constexpr auto NoSatelliteSignalBlinkingAnimation = 0x7d8; // Size: 8, Type: struct UWidgetAnimation*
			constexpr auto ZoomInMapSoundEvent = 0x7e0; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto ZoomOutMapSoundEvent = 0x808; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
	}
} 
