namespace offsets
{
	namespace UWTLGameInstance
	{
			constexpr auto m_ClanList = 0x2d0; // Size: 56, Type: struct FWTLClanList
			constexpr auto m_ClanIcons = 0x308; // Size: 80, Type: struct TMap<uint16_t, struct FWTLClanIcons>
			constexpr auto m_SteamItemDefinitions = 0x378; // Size: 56, Type: struct FWTLSteamInventoryItemList
			constexpr auto m_AccountInventory = 0x3b0; // Size: 64, Type: struct FWTLAccountInventoryItemList
			constexpr auto m_StoreItemList = 0x3f0; // Size: 56, Type: struct FWTLStoreItemList
			constexpr auto m_LoadingScreenLocationWidget = 0x568; // Size: 8, Type: struct UWTLLoadingScreenLocation*
			constexpr auto m_LoadingScreenSimpleWidget = 0x570; // Size: 8, Type: struct UWTLLoadingScreenSimple*
			constexpr auto AmbientEvent = 0x590; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto EventPointsEvent = 0x5c0; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto EventPointsSnapshotEvent = 0x5e8; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto MasterBus = 0x720; // Size: 8, Type: struct UFMODBus*
			constexpr auto MusicBus = 0x728; // Size: 8, Type: struct UFMODBus*
			constexpr auto EffectsBus = 0x730; // Size: 8, Type: struct UFMODBus*
			constexpr auto CharacterVoiceBus = 0x738; // Size: 8, Type: struct UFMODBus*
			constexpr auto SpeechBus = 0x740; // Size: 8, Type: struct UFMODBus*
			constexpr auto UIBus = 0x748; // Size: 8, Type: struct UFMODBus*
			constexpr auto HitEffects = 0x750; // Size: 16, Type: struct TArray<struct FWTLBulletImpactEffect>
			constexpr auto RicochetEffects = 0x760; // Size: 16, Type: struct TArray<struct FWTLBulletImpactEffect>
			constexpr auto FootstepEffects = 0x770; // Size: 16, Type: struct TArray<struct FWTLFootstepEffect>
			constexpr auto BulletFlyNearEffects = 0x780; // Size: 16, Type: struct TArray<struct FWTLBulletFlyNearEffect>
			constexpr auto CharacterDamageEffects = 0x790; // Size: 16, Type: struct TArray<struct FWTLCharacterDamageEffect>
			constexpr auto KnifeHitEffects = 0x7a0; // Size: 16, Type: struct TArray<struct FWTLKnifeImpactEffect>
			constexpr auto CommonButtonSounds = 0x7b0; // Size: 16, Type: struct TArray<struct FWTLCommonButtonSound>
			constexpr auto CommonClickedItemSounds = 0x7c0; // Size: 16, Type: struct TArray<struct FWTLCommonClickedItemSound>
			constexpr auto SwitcherSounds = 0x7d0; // Size: 16, Type: struct TArray<struct FWTLSwitcherSound>
			constexpr auto CheckBoxSounds = 0x7e0; // Size: 16, Type: struct TArray<struct FWTLCheckBoxSound>
			constexpr auto ComboBoxStringSounds = 0x7f0; // Size: 16, Type: struct TArray<struct FWTLComboBoxStringSound>
			constexpr auto DefaultClassesParameters = 0x800; // Size: 80, Type: struct TMap<enum class EWTLCharacterClass, struct FWTLDefaultClassParameters>
			constexpr auto MaleDefaultHeadPartID = 0x850; // Size: 4, Type: int32_t
			constexpr auto MaleDefaultTorsoPartID = 0x854; // Size: 4, Type: int32_t
			constexpr auto MaleDefaultLegsPartID = 0x858; // Size: 4, Type: int32_t
			constexpr auto MaleDefaultFeetPartID = 0x85c; // Size: 4, Type: int32_t
			constexpr auto MaleDefaultGlassesPartID = 0x860; // Size: 4, Type: int32_t
			constexpr auto MaleDefaultWatchesPartID = 0x864; // Size: 4, Type: int32_t
			constexpr auto MaleMinerDefaultBackpackPartID = 0x868; // Size: 4, Type: int32_t
			constexpr auto MaleHunterDefaultBackpackPartID = 0x86c; // Size: 4, Type: int32_t
			constexpr auto MaleMercenaryDefaultBackpackPartID = 0x870; // Size: 4, Type: int32_t
			constexpr auto MaleEngineerDefaultBackpackPartID = 0x874; // Size: 4, Type: int32_t
			constexpr auto FemaleDefaultHeadPartID = 0x878; // Size: 4, Type: int32_t
			constexpr auto FemaleDefaultTorsoPartID = 0x87c; // Size: 4, Type: int32_t
			constexpr auto FemaleDefaultLegsPartID = 0x880; // Size: 4, Type: int32_t
			constexpr auto FemaleDefaultFeetPartID = 0x884; // Size: 4, Type: int32_t
			constexpr auto FemaleDefaultGlassesPartID = 0x888; // Size: 4, Type: int32_t
			constexpr auto FemaleDefaultWatchesPartID = 0x88c; // Size: 4, Type: int32_t
			constexpr auto FemaleMinerDefaultBackpackPartID = 0x890; // Size: 4, Type: int32_t
			constexpr auto FemaleHunterDefaultBackpackPartID = 0x894; // Size: 4, Type: int32_t
			constexpr auto FemaleMercenaryDefaultBackpackPartID = 0x898; // Size: 4, Type: int32_t
			constexpr auto FemaleEngineerDefaultBackpackPartID = 0x89c; // Size: 4, Type: int32_t
			constexpr auto MaleHairDefaultColor = 0x8a0; // Size: 16, Type: struct FLinearColor
			constexpr auto FemaleHairDefaultColor = 0x8b0; // Size: 16, Type: struct FLinearColor
			constexpr auto SkinDefaultColor = 0x8c0; // Size: 16, Type: struct FLinearColor
			constexpr auto DebugPlatform = 0x8d0; // Size: 1, Type: enum class EWTLPlatform
			constexpr auto DebugViewportPositionForUI = 0x8d1; // Size: 1, Type: bool
			constexpr auto DebugIsFounder = 0x8d2; // Size: 1, Type: bool
			constexpr auto DebugHavePremium = 0x8d3; // Size: 1, Type: bool
			constexpr auto IsUseDebugCreditsAmount = 0x8d4; // Size: 1, Type: bool
			constexpr auto DebugCreditsAmount = 0x8d8; // Size: 4, Type: int32_t
			constexpr auto DebugShowHiddenStoreItems = 0x8dc; // Size: 1, Type: bool
			constexpr auto DebugCharacterPlayerType = 0x8dd; // Size: 1, Type: enum class EWTLPlayerType
			constexpr auto DebugCharacterCreationDate = 0x8e0; // Size: 8, Type: struct FWTLDateTime
			constexpr auto DebugCharacterSex = 0x8e8; // Size: 1, Type: enum class EWTLSex
			constexpr auto DebugCharacterLevel = 0x8ec; // Size: 4, Type: int32_t
			constexpr auto DebugCharacterClass = 0x8f0; // Size: 1, Type: enum class EWTLCharacterClass
			constexpr auto DebugCharacterBodyType = 0x8f4; // Size: 4, Type: int32_t
			constexpr auto DebugCharacterFaction = 0x8f8; // Size: 1, Type: enum class EWTLFaction
			constexpr auto DebugCharacterIsInClan = 0x8f9; // Size: 1, Type: bool
			constexpr auto DebugCharacterClanID = 0x8fc; // Size: 4, Type: int32_t
			constexpr auto DebugCharacterClanMemberType = 0x900; // Size: 1, Type: enum class EWTLClanMemberType
			constexpr auto DebugCharacterClanInfoArray = 0x908; // Size: 16, Type: struct TArray<struct FWTLDebugCharacterClanInfo>
			constexpr auto DebugCharacterID = 0x918; // Size: 4, Type: int32_t
			constexpr auto DebugCheckMinLevelAndTimeForBarterAndUseMailBox = 0x91c; // Size: 1, Type: bool
			constexpr auto DebugCharacterCanUseAllItems = 0x91d; // Size: 1, Type: bool
			constexpr auto bIsDebugDisablePlayInEditorCheckingInMainMenuCustomization = 0x91e; // Size: 1, Type: bool
			constexpr auto DebugGameServerID = 0x920; // Size: 4, Type: int32_t
			constexpr auto DebugCreditsToMoneyRate = 0x924; // Size: 4, Type: int32_t
			constexpr auto DebugVOIPTestHost = 0x928; // Size: 16, Type: struct FString
			constexpr auto DebugVOIPTestPort = 0x938; // Size: 4, Type: int32_t
			constexpr auto DebugVOIPTestGUID = 0x940; // Size: 16, Type: struct FString
			constexpr auto AuthorizationInfo = 0x950; // Size: 296, Type: struct FWTLClientAuthorizationResult
			constexpr auto LocalCharactersData = 0xa80; // Size: 80, Type: struct FWTLLocalCharactersData
			constexpr auto Settings = 0xaf0; // Size: 1056, Type: struct FWTLSettings
			constexpr auto SecurityController = 0xf10; // Size: 8, Type: struct UWTLSecurityController*
			constexpr auto NetworkController = 0xf18; // Size: 8, Type: struct UWTLNetworkController*
			constexpr auto VoiceController = 0xf20; // Size: 8, Type: struct UWTLVoiceController*
			constexpr auto SharedData = 0xf28; // Size: 8, Type: struct UWTLSharedData*
			constexpr auto ExperienceSystem = 0xf30; // Size: 8, Type: struct UWTLExperienceSystem*
			constexpr auto SkillSystem = 0xf38; // Size: 8, Type: struct UWTLSkillSystem*
			constexpr auto BallisticsSystem = 0xf40; // Size: 8, Type: struct UWTLBallisticsSystem*
			constexpr auto DamageSystem = 0xf48; // Size: 8, Type: struct UWTLDamageSystem*
			constexpr auto ItemSystem = 0xf50; // Size: 8, Type: struct UWTLItemSystem*
			constexpr auto AchievementSystem = 0xf58; // Size: 8, Type: struct UWTLAchievementSystem*
			constexpr auto EconomicsSystem = 0xf60; // Size: 8, Type: struct UWTLEconomicsSystem*
			constexpr auto QuestSystem = 0xf68; // Size: 8, Type: struct UWTLQuestSystem*
			constexpr auto ReputationSystem = 0xf70; // Size: 8, Type: struct UWTLReputationSystem*
			constexpr auto RankSystem = 0xf78; // Size: 8, Type: struct UWTLRankSystem*
			constexpr auto SecuritySystem = 0xf80; // Size: 8, Type: struct UWTLSecuritySystem*
			constexpr auto StatisticsSystem = 0xf88; // Size: 8, Type: struct UWTLStatisticsSystem*
			constexpr auto GeoSystem = 0xf90; // Size: 8, Type: struct UWTLGeoSystem*
			constexpr auto CharacterEffectsSystem = 0xf98; // Size: 8, Type: struct UWTLCharacterEffectsSystem*
			constexpr auto CustomizationSystem = 0xfa0; // Size: 8, Type: struct UWTLCustomizationSystem*
			constexpr auto DatabaseAdapter = 0xfa8; // Size: 8, Type: struct UWTLDatabaseAdapter*
			constexpr auto MailSystem = 0xfb0; // Size: 8, Type: struct UWTLMailSystem*
			constexpr auto SocialSystem = 0xfb8; // Size: 8, Type: struct UWTLSocialSystem*
			constexpr auto CommandSystem = 0xfc0; // Size: 8, Type: struct UWTLCommandSystem*
			constexpr auto HighlightsLibrary = 0xfc8; // Size: 8, Type: struct UWTLNvidiaHighlightsLibrary*
			constexpr auto ScriptedEventsSystem = 0xfd0; // Size: 8, Type: struct UWTLScriptedEventsSystem*
			constexpr auto SocialNetworkAdapters = 0xfd8; // Size: 80, Type: struct TMap<enum class EWTLSocialNetworkType, struct UWTLSocialNetworkAdapter*>
			constexpr auto DevelopmentStage = 0x1028; // Size: 24, Type: struct FText
			constexpr auto LoadingScreenLocationWidgetClass = 0x1040; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto LoadingScreenSimpleWidgetClass = 0x1068; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto RainDensityScaleByRainAlpha = 0x1090; // Size: 8, Type: struct UCurveFloat*
			constexpr auto RainDensityScaleByHeavyRainAlpha = 0x1098; // Size: 8, Type: struct UCurveFloat*
			constexpr auto RainParticleSystem = 0x10a0; // Size: 40, Type: struct TSoftObjectPtr<UParticleSystem>
			constexpr auto RainAmbientSoundEvent = 0x10c8; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto SandStormAmbientSoundEvent = 0x10f0; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto WindAmbientSoundEvent = 0x1118; // Size: 40, Type: struct TSoftObjectPtr<UFMODEvent>
			constexpr auto SkyBlueprintClass = 0x1140; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto LightingBoltBlueprintClass = 0x1168; // Size: 40, Type: struct TSoftClassPtr<UObject>
			constexpr auto DefaultMarkerTexture = 0x1190; // Size: 40, Type: struct TSoftObjectPtr<UTexture2D>
			constexpr auto Markers = 0x11b8; // Size: 16, Type: struct TArray<struct FWTLMarkerInfo>
	}
} 
