namespace offsets
{
	namespace UWTLCharacterBodyAnimInstance
	{
			constexpr auto CharacterProxy = 0x300; // Size: 1904, Type: struct FWTLCharacterAnimInstanceProxy
			constexpr auto WeaponItemRemap = 0xa70; // Size: 80, Type: struct TMap<uint16_t, uint16_t>
			constexpr auto StuffItemRemap = 0xac0; // Size: 80, Type: struct TMap<uint16_t, uint16_t>
			constexpr auto IsFirstPerson = 0xb10; // Size: 1, Type: bool
			constexpr auto CharacterSex = 0xb11; // Size: 1, Type: enum class EWTLSex
			constexpr auto LookDirection = 0xb14; // Size: 12, Type: struct FVector
			constexpr auto CameraAimOffset = 0xb20; // Size: 4, Type: float
			constexpr auto CameraAimOffsetInterpSpeedMultiplier = 0xb24; // Size: 4, Type: float
			constexpr auto MoveDirection = 0xb28; // Size: 4, Type: float
			constexpr auto SnuggleValue = 0xb2c; // Size: 4, Type: float
			constexpr auto MovementSpeed = 0xb30; // Size: 4, Type: float
			constexpr auto VelocityZ = 0xb34; // Size: 4, Type: float
			constexpr auto BodyTilt = 0xb38; // Size: 4, Type: float
			constexpr auto bIsInAir = 0xb3c; // Size: 1, Type: bool
			constexpr auto bIsUnderWater = 0xb3d; // Size: 1, Type: bool
			constexpr auto bIsInWater = 0xb3e; // Size: 1, Type: bool
			constexpr auto bMovesOnWater = 0xb3f; // Size: 1, Type: bool
			constexpr auto bIsAiming = 0xb40; // Size: 1, Type: bool
			constexpr auto bIsCrouch = 0xb41; // Size: 1, Type: bool
			constexpr auto bIsProne = 0xb42; // Size: 1, Type: bool
			constexpr auto bIsJumping = 0xb43; // Size: 1, Type: bool
			constexpr auto bIsSprinting = 0xb44; // Size: 1, Type: bool
			constexpr auto bIsLadderClimbing = 0xb45; // Size: 1, Type: bool
			constexpr auto InputVector = 0xb48; // Size: 12, Type: struct FVector
			constexpr auto MoveSpeedValue = 0xb54; // Size: 4, Type: float
			constexpr auto MoveTurnValue = 0xb58; // Size: 4, Type: float
			constexpr auto MovementState = 0xb5c; // Size: 1, Type: enum class EWTLCharacterMoveState
			constexpr auto HoldingBreath = 0xb60; // Size: 4, Type: float
			constexpr auto StaminaValue = 0xb64; // Size: 4, Type: float
			constexpr auto TirednessValue = 0xb68; // Size: 4, Type: float
			constexpr auto TirednessValueMultiplier = 0xb6c; // Size: 4, Type: float
			constexpr auto AnimationCurve = 0xb70; // Size: 8, Type: struct UCurveVector*
			constexpr auto CurrentWeaponRotation = 0xb78; // Size: 12, Type: struct FRotator
			constexpr auto HandsState = 0xb84; // Size: 1, Type: enum class EWTLHandsState
			constexpr auto ItemEquipTime = 0xb88; // Size: 4, Type: float
			constexpr auto ItemUnequipTime = 0xb8c; // Size: 4, Type: float
			constexpr auto LeftHandThumbInputUp = 0xb90; // Size: 4, Type: float
			constexpr auto LeftHandThumbInputRight = 0xb94; // Size: 4, Type: float
			constexpr auto CanUseHandsLocomotion = 0xb98; // Size: 1, Type: bool
			constexpr auto IKRightFootAlphaCurveName = 0xb9c; // Size: 8, Type: struct FName
			constexpr auto IKLeftFootAlphaCurveName = 0xba4; // Size: 8, Type: struct FName
			constexpr auto IKRightKneeSocketName = 0xbac; // Size: 8, Type: struct FName
			constexpr auto IKLeftKneeSocketName = 0xbb4; // Size: 8, Type: struct FName
			constexpr auto IKHipInterpSpeed = 0xbbc; // Size: 4, Type: float
			constexpr auto IKEffectorPositionInterpSpeed = 0xbc0; // Size: 4, Type: float
			constexpr auto IKAlphaInterpSpeed = 0xbc4; // Size: 4, Type: float
			constexpr auto IKFootNormalInterpSpeed = 0xbc8; // Size: 4, Type: float
			constexpr auto IKHipOffset = 0xbcc; // Size: 4, Type: float
			constexpr auto IKFloorTraceValue = 0xbd4; // Size: 4, Type: float
			constexpr auto IKHipTarget = 0xbd8; // Size: 12, Type: struct FVector
			constexpr auto IKRightFootEffectorPosition = 0xbe4; // Size: 12, Type: struct FVector
			constexpr auto IKLeftFootEffectorPosition = 0xbfc; // Size: 12, Type: struct FVector
			constexpr auto IKRightKneePosition = 0xc14; // Size: 12, Type: struct FVector
			constexpr auto IKLeftKneePosition = 0xc20; // Size: 12, Type: struct FVector
			constexpr auto IKRightFootNormal = 0xc2c; // Size: 12, Type: struct FVector
			constexpr auto IKLeftFootNormal = 0xc44; // Size: 12, Type: struct FVector
			constexpr auto bIKRightFootHit = 0xc5c; // Size: 1, Type: bool
			constexpr auto bIKLeftFootHit = 0xc5d; // Size: 1, Type: bool
			constexpr auto IKRightFootAlpha = 0xc60; // Size: 4, Type: float
			constexpr auto IKLeftFootAlpha = 0xc64; // Size: 4, Type: float
			constexpr auto IKHandsOffsetBoneName = 0xc68; // Size: 8, Type: struct FName
			constexpr auto IKHandsOffsetBoneTransform = 0xc70; // Size: 48, Type: struct FTransform
			constexpr auto UsableItemID = 0xca0; // Size: 4, Type: int32_t
			constexpr auto LastUsableItemID = 0xca4; // Size: 4, Type: int32_t
			constexpr auto UsableItemType = 0xca8; // Size: 1, Type: enum class EWTLItemType
			constexpr auto UsableItemAnimationFloatParameters = 0xcb0; // Size: 16, Type: struct TArray<float>
			constexpr auto UsableItemAnimationVectorParameters = 0xcc0; // Size: 16, Type: struct TArray<struct FVector>
			constexpr auto HandsOffset = 0xcd0; // Size: 12, Type: struct FVector
			constexpr auto CurrentWeaponType = 0xcdc; // Size: 1, Type: enum class EWTLWeaponType
			constexpr auto RotationSpeedVertical = 0xce0; // Size: 4, Type: float
			constexpr auto RecoilTranslation = 0xce4; // Size: 12, Type: struct FVector
			constexpr auto RecoilRotation = 0xcf0; // Size: 12, Type: struct FRotator
			constexpr auto IdleAnimation = 0xd00; // Size: 8, Type: struct UAnimSequence*
			constexpr auto SnuggleAnimation = 0xd08; // Size: 8, Type: struct UAnimSequence*
			constexpr auto AimOffsetBlendSpace = 0xd10; // Size: 8, Type: struct UAimOffsetBlendSpace1D*
			constexpr auto AimingHandsTranslation = 0xd18; // Size: 12, Type: struct FVector
			constexpr auto AimingHandsOffset = 0xd24; // Size: 12, Type: struct FVector
			constexpr auto MissileSocketOffset = 0xd30; // Size: 12, Type: struct FVector
			constexpr auto ThumbLOffset = 0xd3c; // Size: 12, Type: struct FVector
			constexpr auto ThumbROffset = 0xd48; // Size: 12, Type: struct FVector
			constexpr auto FirstSwingingAnimAlphaScaleParameter = 0xd54; // Size: 4, Type: float
			constexpr auto SecondSwingingAnimAlphaScaleParameter = 0xd58; // Size: 4, Type: float
			constexpr auto ThirdPersonSwingingAnimAlphaParameter = 0xd5c; // Size: 4, Type: float
			constexpr auto FirstPersonSwingingAnimAlphaParameter = 0xd60; // Size: 4, Type: float
			constexpr auto CombatBreathAnimPlayRateScaleParameter = 0xd64; // Size: 4, Type: float
			constexpr auto CombatBreathAnimPlayRateMaxValueParameter = 0xd68; // Size: 4, Type: float
			constexpr auto CombatBreathAnimPlayRateMinValueParameter = 0xd6c; // Size: 4, Type: float
			constexpr auto ThirdPersonCombatBreathAnimAimingAlphaMaxValueParameter = 0xd70; // Size: 4, Type: float
			constexpr auto ThirdPersonCombatBreathAnimAimingAlphaMinValueParameter = 0xd74; // Size: 4, Type: float
			constexpr auto FirstPersonCombatBreathAnimAlphaParameter = 0xd78; // Size: 4, Type: float
			constexpr auto ThirdPersonWeaponRotationAnimAlphaParameter = 0xd7c; // Size: 4, Type: float
			constexpr auto FirstPersonWeaponRotationAnimStaminaAlphaMinValueParameter = 0xd80; // Size: 4, Type: float
			constexpr auto FirstPersonWeaponRotationAnimStaminaAlphaMaxValueParameter = 0xd84; // Size: 4, Type: float
			constexpr auto FirstPersonWeaponRotationAnimAimingAlphaMinValueParameter = 0xd88; // Size: 4, Type: float
			constexpr auto FirstPersonWeaponRotationAnimAimingAlphaMaxValueParameter = 0xd8c; // Size: 4, Type: float
			constexpr auto WeaponRotationLocomotionAimingAlphaMinValueParameter = 0xd90; // Size: 4, Type: float
			constexpr auto WeaponRotationLocomotionAimingAlphaMaxValueParameter = 0xd94; // Size: 4, Type: float
			constexpr auto WeaponRotationLocomotionHoldingBreathAlphaMinValueParameter = 0xd98; // Size: 4, Type: float
			constexpr auto WeaponRotationLocomotionHoldingBreathAlphaMaxValueParameter = 0xd9c; // Size: 4, Type: float
			constexpr auto RightPocketLocationSocketName = 0xda0; // Size: 8, Type: struct FName
			constexpr auto LeftPocketLocationSocketName = 0xda8; // Size: 8, Type: struct FName
			constexpr auto LeftJointTargetSocketName = 0xdb0; // Size: 8, Type: struct FName
			constexpr auto RightJointTargetSocketName = 0xdb8; // Size: 8, Type: struct FName
			constexpr auto AimingRecoilAlphaMinValueParameter = 0xdc0; // Size: 4, Type: float
			constexpr auto AimingRecoilAlphaMaxValueParameter = 0xdc4; // Size: 4, Type: float
			constexpr auto ThirdPersonStaminaValueAnimPlayRateMinValueParameter = 0xdc8; // Size: 4, Type: float
			constexpr auto ThirdPersonStaminaValueAnimPlayRateMaxValueParameter = 0xdcc; // Size: 4, Type: float
			constexpr auto WeaponRotationAimOffsetVelocityMinValueParameter = 0xdd0; // Size: 4, Type: float
			constexpr auto WeaponRotationAimOffsetVelocityMaxValueParameter = 0xdd4; // Size: 4, Type: float
			constexpr auto StaminaInterpolationSpeed = 0xdd8; // Size: 4, Type: float
			constexpr auto NonSprintingSpeedTreshold = 0xddc; // Size: 4, Type: float
			constexpr auto FloorNormal = 0xde0; // Size: 12, Type: struct FVector
			constexpr auto DotPCapsule = 0xdec; // Size: 4, Type: float
			constexpr auto DotPRightFoot = 0xdf0; // Size: 4, Type: float
			constexpr auto DotPLeftFoot = 0xdf4; // Size: 4, Type: float
			constexpr auto ForwardVelocity = 0xdf8; // Size: 4, Type: float
			constexpr auto SideVelocity = 0xdfc; // Size: 4, Type: float
			constexpr auto LowerBodyRelativeAngle = 0xe00; // Size: 4, Type: float
			constexpr auto LowerBodyFixedRelativeAngle = 0xe04; // Size: 4, Type: float
			constexpr auto LocomotionState = 0xe08; // Size: 1, Type: enum class EWTLCharacterAnimationInstanceMovementState
			constexpr auto RotationSpeedHorizontalWithDirection = 0xe0c; // Size: 4, Type: float
			constexpr auto OneMinusIsNoMovementCurveValue = 0xe10; // Size: 4, Type: float
			constexpr auto OneMinusEmptyHandsCurveValue = 0xe14; // Size: 4, Type: float
			constexpr auto AimingRecoilAlpha = 0xe18; // Size: 4, Type: float
			constexpr auto ThirdPersonStaminaValueAnimPlayRate = 0xe1c; // Size: 4, Type: float
			constexpr auto IsNotFirstPersonAlpha = 0xe20; // Size: 4, Type: float
			constexpr auto WeaponRotationAimOffsetForwardVelocity = 0xe24; // Size: 4, Type: float
			constexpr auto WeaponRotationAimOffsetSideVelocity = 0xe28; // Size: 4, Type: float
			constexpr auto CombatBreathAnimPlayRate = 0xe2c; // Size: 4, Type: float
			constexpr auto CombatBreathAnimAlpha = 0xe30; // Size: 4, Type: float
			constexpr auto WeaponRotationAnimAlpha = 0xe34; // Size: 4, Type: float
			constexpr auto WeaponRotationLocomotionAlpha = 0xe38; // Size: 4, Type: float
			constexpr auto AimOffsetBoneRotation = 0xe3c; // Size: 12, Type: struct FRotator
			constexpr auto AimingAlphaCurveValue = 0xe48; // Size: 4, Type: float
			constexpr auto bIsInCombatMode = 0xe4c; // Size: 1, Type: bool
			constexpr auto FirstSwingAnimAlpha = 0xe50; // Size: 4, Type: float
			constexpr auto SecondSwingAnimAlpha = 0xe54; // Size: 4, Type: float
			constexpr auto AimOffsetBoneRotationAlpha = 0xe58; // Size: 4, Type: float
			constexpr auto HandsTranslationOffset = 0xe5c; // Size: 12, Type: struct FVector
			constexpr auto OneMinusAimingAlphaCurveValue = 0xe68; // Size: 4, Type: float
			constexpr auto AimingHandsTranslationOffset = 0xe6c; // Size: 12, Type: struct FVector
			constexpr auto HandsAimOffsetDownTranslationOffset = 0xe78; // Size: 12, Type: struct FVector
			constexpr auto HandsAimOffsetDownAlpha = 0xe84; // Size: 4, Type: float
			constexpr auto RightPocketLocation = 0xe88; // Size: 12, Type: struct FVector
			constexpr auto LeftPocketLocation = 0xe94; // Size: 12, Type: struct FVector
			constexpr auto LeftJointTargetLocation = 0xea0; // Size: 12, Type: struct FVector
			constexpr auto RightJointTargetLocation = 0xeac; // Size: 12, Type: struct FVector
			constexpr auto RightHandAlphaCurveValue = 0xeb8; // Size: 4, Type: float
			constexpr auto LeftHandAlphaCurveValue = 0xebc; // Size: 4, Type: float
			constexpr auto LowerBodyRotation = 0xec0; // Size: 12, Type: struct FRotator
			constexpr auto IKFootRootBoneRotation = 0xecc; // Size: 12, Type: struct FRotator
			constexpr auto PelvisOffset = 0xed8; // Size: 12, Type: struct FVector
			constexpr auto RightFootRotation = 0xee4; // Size: 12, Type: struct FRotator
			constexpr auto LeftFootRotation = 0xef0; // Size: 12, Type: struct FRotator
			constexpr auto LadderLoopAnimPlayRate = 0xefc; // Size: 4, Type: float
			constexpr auto IsLadderNoMovement = 0xf00; // Size: 1, Type: bool
			constexpr auto ScaleRibCageVector = 0xf04; // Size: 12, Type: struct FVector
			constexpr auto InvertScaleRibCageVector = 0xf10; // Size: 12, Type: struct FVector
			constexpr auto ScaleNeckVector = 0xf1c; // Size: 12, Type: struct FVector
			constexpr auto ScaleHeadVector = 0xf28; // Size: 12, Type: struct FVector
			constexpr auto ScaleHandsVector = 0xf34; // Size: 12, Type: struct FVector
			constexpr auto InvertScaleHandsVector = 0xf40; // Size: 12, Type: struct FVector
			constexpr auto ScaleFeetVector = 0xf4c; // Size: 12, Type: struct FVector
			constexpr auto InvertScaleFeetVector = 0xf58; // Size: 12, Type: struct FVector
			constexpr auto bIsUnequip = 0xf64; // Size: 1, Type: bool
			constexpr auto FIsUnequip = 0xf68; // Size: 4, Type: float
			constexpr auto FScaleNeck = 0xf6c; // Size: 4, Type: float
			constexpr auto FScaleHead = 0xf70; // Size: 4, Type: float
			constexpr auto FScaleRibCage = 0xf74; // Size: 4, Type: float
			constexpr auto FScaleBody = 0xf78; // Size: 4, Type: float
			constexpr auto FScaleHands = 0xf7c; // Size: 4, Type: float
			constexpr auto FScaleFeet = 0xf80; // Size: 4, Type: float
			constexpr auto FTiltXWithFishingRod = 0xf84; // Size: 4, Type: float
			constexpr auto FTiltYWithFishingRod = 0xf88; // Size: 4, Type: float
			constexpr auto FRodResistanceValue = 0xf8c; // Size: 4, Type: float
			constexpr auto InFishingMode = 0xf90; // Size: 1, Type: bool
			constexpr auto NowIsFishing = 0xf91; // Size: 1, Type: bool
			constexpr auto ShowCathedFish = 0xf92; // Size: 1, Type: bool
			constexpr auto Complexion = 0xf94; // Size: 4, Type: int32_t
	}
} 
